#!/bin/sh
# docker/redis/redis-entrypoint.sh
#
# Renders users.acl from the template by substituting REDIS_PASSWORD_* placeholders
# with passwords generated by op-init, then starts redis-server.
#
# The template lives at /etc/redis/users.acl.template (read-only mount).
# The rendered ACL is written to /tmp/users.acl so it resides on a writable
# tmpfs rather than a read-only config volume.
#
# Ref spec §3 "Redis: ACL Users", §2 "Startup Sequence".

set -e

INIT_DIR="/data/init"
TEMPLATE="/etc/redis/users.acl.template"
RENDERED="/tmp/users.acl"

# Fail loudly if op-init did not complete — Redis must not start without ACLs.
if [ ! -f "$INIT_DIR/ready" ]; then
  echo "[redis-entrypoint] FATAL: op-init has not completed ($INIT_DIR/ready missing)." >&2
  exit 1
fi

echo "[redis-entrypoint] Rendering users.acl from template..."

cp "$TEMPLATE" "$RENDERED"

for USER in admin auth pipeline logging gateway ingestion ontology app plugin execution; do
  PW_FILE="$INIT_DIR/redis_password_${USER}.txt"
  if [ ! -f "$PW_FILE" ]; then
    echo "[redis-entrypoint] FATAL: Redis password file missing: $PW_FILE" >&2
    exit 1
  fi
  PW=$(tr -d '[:space:]' < "$PW_FILE")
  # Use | as sed delimiter to avoid conflicts with any characters in passwords
  sed -i "s|REDIS_PASSWORD_${USER}|${PW}|g" "$RENDERED"
done

# Guard: if any placeholder survives, a password file was missed — refuse to start.
if grep -q 'REDIS_PASSWORD_' "$RENDERED"; then
  echo "[redis-entrypoint] FATAL: Unreplaced REDIS_PASSWORD_ placeholder in rendered ACL." >&2
  exit 1
fi

echo "[redis-entrypoint] users.acl rendered successfully. Starting redis-server..."

exec redis-server /etc/redis/redis.conf --aclfile "$RENDERED" "$@"
