// ---------------------------------------------------------------------------
// Activity Feed template — G-075 / NCD-002
//
// Produces a page header (title, count), a filter bar by event type, and
// a chronological list of activity events with actor, action, resource,
// and relative time. Designed for audit logs, event streams, or any
// time-series entity.
// ---------------------------------------------------------------------------

import type { AppTemplate } from "./types.js";
import { escapeForTemplateLiteral } from "./escape.js";

export const activityFeedTemplate: AppTemplate = {
  meta: {
    id:          "activity-feed",
    name:        "Activity Feed",
    description: "Chronological event stream with type filter and relative timestamps. Connect to any event or log entity.",
    category:    "dashboard",
    thumbnail:   "/assets/templates/activity-feed.png",
    requiredPermissions: ["entity:read"],
  },

  render(appName: string, slug: string): Record<string, string> {
    const safeName = escapeForTemplateLiteral(appName);
    return {
      "/package.json": JSON.stringify(
        {
          name: slug,
          version: "0.1.0",
          dependencies: {
            react: "^18.2.0",
            "react-dom": "^18.2.0",
            "@oneplatform/app-sdk": "^1.0.0",
          },
        },
        null,
        2
      ),

      "/tsconfig.json": JSON.stringify(
        {
          compilerOptions: {
            target: "ES2022",
            module: "ESNext",
            moduleResolution: "bundler",
            jsx: "react-jsx",
            strict: true,
            esModuleInterop: true,
            allowSyntheticDefaultImports: true,
          },
          include: ["src"],
        },
        null,
        2
      ),

      "/src/index.tsx": [
        `import React from "react";`,
        `import { createRoot } from "react-dom/client";`,
        `import { AppProvider } from "@oneplatform/app-sdk";`,
        `import { App } from "./App.js";`,
        ``,
        `const container = document.getElementById("app");`,
        `if (!container) throw new Error("Root element #app not found");`,
        `createRoot(container).render(<AppProvider><App /></AppProvider>);`,
      ].join("\n"),

      "/src/App.tsx": [
        `/**`,
        ` * Replace "events" with your actual entity name.`,
        ` * Expected fields: id, type (string), actor (string), resource (string),`,
        ` * message (string | null), timestamp (ISO string).`,
        ` */`,
        `import React, { useState } from "react";`,
        `import { useQuery } from "@oneplatform/app-sdk";`,
        `import { FeedList } from "./components/FeedList.js";`,
        `import { relativeTime } from "./lib/time.js";`,
        ``,
        `export interface ActivityEvent {`,
        `  id:        string;`,
        `  type:      string;`,
        `  actor:     string;`,
        `  resource:  string;`,
        `  message:   string | null;`,
        `  timestamp: string;`,
        `}`,
        ``,
        `export { relativeTime };`,
        ``,
        `export function App() {`,
        `  const [typeFilter, setTypeFilter] = useState<string>("all");`,
        `  const [visibleCount, setVisibleCount] = useState(20);`,
        `  const { data, isLoading, error, refetch } = useQuery<ActivityEvent>("events");`,
        ``,
        `  if (isLoading) return <div style={wrap}><p>Loading activity…</p></div>;`,
        `  if (error)     return <div style={wrap}><p style={{ color: "red" }}>Error: {error.message}</p></div>;`,
        ``,
        `  // Sort newest first`,
        `  const sorted = [...data].sort((a, b) => b.timestamp.localeCompare(a.timestamp));`,
        `  const types  = Array.from(new Set(sorted.map((e) => e.type)));`,
        `  const filtered = typeFilter === "all" ? sorted : sorted.filter((e) => e.type === typeFilter);`,
        `  const visible  = filtered.slice(0, visibleCount);`,
        `  const hasMore  = visibleCount < filtered.length;`,
        ``,
        `  return (`,
        `    <div style={wrap}>`,
        `      {/* Page header */}`,
        `      <div style={{ display: "flex", alignItems: "baseline", justifyContent: "space-between", marginBottom: "16px" }}>`,
        `        <h1 style={{ fontSize: "1.5rem", fontWeight: 700 }}>${safeName}</h1>`,
        `        <span style={{ fontSize: "0.875rem", color: "#64748b" }}>{filtered.length} event{filtered.length !== 1 ? "s" : ""}</span>`,
        `      </div>`,
        ``,
        `      {/* Filter bar */}`,
        `      <div style={{ display: "flex", gap: "8px", marginBottom: "20px", flexWrap: "wrap" }}>`,
        `        {["all", ...types].map((t) => (`,
        `          <button`,
        `            key={t}`,
        `            onClick={() => { setTypeFilter(t); setVisibleCount(20); }}`,
        `            style={{`,
        `              padding: "5px 12px",`,
        `              borderRadius: "9999px",`,
        `              border: "1px solid",`,
        `              fontSize: "0.75rem",`,
        `              fontWeight: typeFilter === t ? 600 : 400,`,
        `              cursor: "pointer",`,
        `              background: typeFilter === t ? "#1e40af" : "#fff",`,
        `              color: typeFilter === t ? "#fff" : "#374151",`,
        `              borderColor: typeFilter === t ? "#1e40af" : "#d1d5db",`,
        `            }}`,
        `          >`,
        `            {t === "all" ? "All types" : t}`,
        `          </button>`,
        `        ))}`,
        `        <button`,
        `          onClick={() => void refetch()}`,
        `          style={{ marginLeft: "auto", padding: "5px 12px", border: "1px solid #d1d5db", borderRadius: "9999px", background: "#fff", fontSize: "0.75rem", cursor: "pointer" }}`,
        `        >`,
        `          Refresh`,
        `        </button>`,
        `      </div>`,
        ``,
        `      <FeedList events={visible} />`,
        ``,
        `      {/* Infinite scroll — load more on demand */}`,
        `      {hasMore && (`,
        `        <div style={{ marginTop: "16px", textAlign: "center" }}>`,
        `          <button`,
        `            onClick={() => setVisibleCount((n) => n + 20)}`,
        `            style={{ padding: "8px 20px", border: "1px solid #d1d5db", borderRadius: "6px", background: "#fff", cursor: "pointer", fontSize: "0.875rem" }}`,
        `          >`,
        `            Load more ({filtered.length - visibleCount} remaining)`,
        `          </button>`,
        `        </div>`,
        `      )}`,
        `    </div>`,
        `  );`,
        `}`,
        ``,
        `const wrap = { padding: "24px", fontFamily: "system-ui, sans-serif", maxWidth: "720px" };`,
      ].join("\n"),

      "/src/components/FeedList.tsx": [
        `import React from "react";`,
        `import type { ActivityEvent } from "../App.js";`,
        `import { relativeTime } from "../App.js";`,
        ``,
        `// Map common event type prefixes to icon characters for quick visual scanning`,
        `function typeIcon(type: string): string {`,
        `  if (type.includes("CREATE"))   return "✚";`,
        `  if (type.includes("UPDATE"))   return "✎";`,
        `  if (type.includes("DELETE"))   return "✕";`,
        `  if (type.includes("LOGIN"))    return "→";`,
        `  if (type.includes("LOGOUT"))   return "←";`,
        `  if (type.includes("RUN"))      return "▶";`,
        `  if (type.includes("FAIL"))     return "✗";`,
        `  return "●";`,
        `}`,
        ``,
        `export function FeedList({ events }: { events: ActivityEvent[] }) {`,
        `  if (events.length === 0) {`,
        `    return <p style={{ color: "#94a3b8", fontSize: "0.875rem" }}>No events match this filter.</p>;`,
        `  }`,
        ``,
        `  return (`,
        `    <ul style={{ listStyle: "none", padding: 0, margin: 0 }}>`,
        `      {events.map((event) => (`,
        `        <li key={event.id} style={{ display: "flex", gap: "12px", padding: "12px 0", borderBottom: "1px solid #f1f5f9" }}>`,
        `          {/* Icon column */}`,
        `          <div style={{ width: "28px", height: "28px", borderRadius: "50%", background: "#eff6ff", display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0, fontSize: "0.75rem", color: "#2563eb" }}>`,
        `            {typeIcon(event.type)}`,
        `          </div>`,
        `          {/* Content */}`,
        `          <div style={{ flex: 1, minWidth: 0 }}>`,
        `            <div style={{ display: "flex", gap: "6px", alignItems: "baseline", flexWrap: "wrap" }}>`,
        `              <span style={{ fontSize: "0.75rem", fontWeight: 600, color: "#1e40af", background: "#dbeafe", padding: "1px 6px", borderRadius: "4px" }}>`,
        `                {event.type}`,
        `              </span>`,
        `              <span style={{ fontSize: "0.875rem", color: "#374151" }}>`,
        `                <strong>{event.actor}</strong> — {event.resource}`,
        `              </span>`,
        `            </div>`,
        `            {event.message !== null && (`,
        `              <p style={{ margin: "4px 0 0", fontSize: "0.8125rem", color: "#64748b" }}>{event.message}</p>`,
        `            )}`,
        `          </div>`,
        `          {/* Timestamp */}`,
        `          <time dateTime={event.timestamp} style={{ fontSize: "0.75rem", color: "#94a3b8", flexShrink: 0 }}>`,
        `            {relativeTime(event.timestamp)}`,
        `          </time>`,
        `        </li>`,
        `      ))}`,
        `    </ul>`,
        `  );`,
        `}`,
      ].join("\n"),

      "/src/lib/time.ts": [
        `// Locale-aware relative time formatting using the Intl.RelativeTimeFormat API.`,
        `// Falls back to ISO string when the API is unavailable (server-side rendering).`,
        ``,
        `const rtf = typeof Intl !== "undefined" && "RelativeTimeFormat" in Intl`,
        `  ? new Intl.RelativeTimeFormat("en", { numeric: "auto" })`,
        `  : null;`,
        ``,
        `export function relativeTime(iso: string): string {`,
        `  if (rtf === null) return iso;`,
        `  const diffMs = new Date(iso).getTime() - Date.now();`,
        `  const diffSec = Math.round(diffMs / 1000);`,
        `  if (Math.abs(diffSec) < 60)  return rtf.format(diffSec, "second");`,
        `  const diffMin = Math.round(diffSec / 60);`,
        `  if (Math.abs(diffMin) < 60)  return rtf.format(diffMin, "minute");`,
        `  const diffHr  = Math.round(diffMin / 60);`,
        `  if (Math.abs(diffHr)  < 24)  return rtf.format(diffHr,  "hour");`,
        `  return rtf.format(Math.round(diffHr / 24), "day");`,
        `}`,
      ].join("\n"),
    };
  },
};
