// ---------------------------------------------------------------------------
// CRUD admin panel template — G-075
//
// Produces a working data table with create / edit / delete modals backed by
// the app-sdk useQuery / useMutation hooks. The "entity" name is left as
// "Record" so users can rename it to match their actual data type without
// touching the SDK plumbing.
// ---------------------------------------------------------------------------

import type { AppTemplate } from "./types.js";
import { escapeForTemplateLiteral } from "./escape.js";

export const crudAdminTemplate: AppTemplate = {
  meta: {
    id:          "crud-admin",
    name:        "CRUD Admin Panel",
    description: "Data table with create, edit, and delete operations. Connects to any entity via the app SDK.",
    category:    "admin",
    thumbnail:   "/assets/templates/crud-admin.png",
    requiredPermissions: ["entity:read", "entity:create", "entity:update", "entity:delete"],
  },

  render(appName: string, slug: string): Record<string, string> {
    const safeName = escapeForTemplateLiteral(appName);
    return {
      "/package.json": JSON.stringify(
        {
          name:    slug,
          version: "0.1.0",
          dependencies: {
            react:             "^18.2.0",
            "react-dom":       "^18.2.0",
            "@oneplatform/app-sdk": "^1.0.0",
          },
        },
        null,
        2
      ),

      "/tsconfig.json": JSON.stringify(
        {
          compilerOptions: {
            target:                   "ES2022",
            module:                   "ESNext",
            moduleResolution:         "bundler",
            jsx:                      "react-jsx",
            strict:                   true,
            esModuleInterop:          true,
            allowSyntheticDefaultImports: true,
          },
          include: ["src"],
        },
        null,
        2
      ),

      "/src/index.tsx": [
        `import React from "react";`,
        `import { createRoot } from "react-dom/client";`,
        `import { AppProvider } from "@oneplatform/app-sdk";`,
        `import { App } from "./App.js";`,
        ``,
        `const container = document.getElementById("app");`,
        `if (!container) throw new Error("Root element #app not found");`,
        ``,
        `createRoot(container).render(`,
        `  <AppProvider>`,
        `    <App />`,
        `  </AppProvider>`,
        `);`,
      ].join("\n"),

      "/src/App.tsx": [
        `import React from "react";`,
        `import { RecordTable } from "./components/RecordTable.js";`,
        ``,
        `export function App() {`,
        `  return (`,
        `    <div style={{ padding: "24px", fontFamily: "system-ui, sans-serif" }}>`,
        `      <h1 style={{ marginBottom: "24px", fontSize: "1.5rem", fontWeight: 700 }}>`,
        `        ${safeName}`,
        `      </h1>`,
        `      <RecordTable />`,
        `    </div>`,
        `  );`,
        `}`,
      ].join("\n"),

      "/src/components/RecordTable.tsx": [
        `/**`,
        ` * RecordTable — full CRUD table connected to the "records" entity.`,
        ` *`,
        ` * Rename the "records" entity key and Record type fields to match your`,
        ` * actual data model. The SDK hooks handle all data fetching and mutations.`,
        ` */`,
        `import React, { useState } from "react";`,
        `import { useQuery, useMutation } from "@oneplatform/app-sdk";`,
        `import { RecordFormModal } from "./RecordFormModal.js";`,
        ``,
        `export interface Record {`,
        `  id:    string;`,
        `  name:  string;`,
        `  value: string;`,
        `}`,
        ``,
        `export function RecordTable() {`,
        `  const { data, isLoading, error, refetch } = useQuery<Record>("records");`,
        `  const mutation = useMutation<Record>("records");`,
        ``,
        `  const [editing, setEditing]   = useState<Record | null>(null);`,
        `  const [creating, setCreating] = useState(false);`,
        ``,
        `  async function handleDelete(id: string): Promise<void> {`,
        `    if (!window.confirm("Delete this record?")) return;`,
        `    try {`,
        `      await mutation.remove(id);`,
        `      refetch();`,
        `    } catch (err) {`,
        `      console.error("Delete failed:", err);`,
        `    }`,
        `  }`,
        ``,
        `  if (isLoading) return <p>Loading…</p>;`,
        `  if (error)     return <p style={{ color: "red" }}>Error: {error.message}</p>;`,
        ``,
        `  return (`,
        `    <div>`,
        `      <div style={{ marginBottom: "16px" }}>`,
        `        <button`,
        `          onClick={() => setCreating(true)}`,
        `          style={{ padding: "8px 16px", background: "#2563eb", color: "#fff", border: "none", borderRadius: "6px", cursor: "pointer" }}`,
        `        >`,
        `          + New record`,
        `        </button>`,
        `      </div>`,
        ``,
        `      <table style={{ width: "100%", borderCollapse: "collapse" }}>`,
        `        <thead>`,
        `          <tr style={{ background: "#f1f5f9" }}>`,
        `            <th style={th}>Name</th>`,
        `            <th style={th}>Value</th>`,
        `            <th style={th}>Actions</th>`,
        `          </tr>`,
        `        </thead>`,
        `        <tbody>`,
        `          {data.map((row) => (`,
        `            <tr key={row.id} style={{ borderBottom: "1px solid #e2e8f0" }}>`,
        `              <td style={td}>{row.name}</td>`,
        `              <td style={td}>{row.value}</td>`,
        `              <td style={td}>`,
        `                <button onClick={() => setEditing(row)} style={btnSecondary}>Edit</button>`,
        `                <button onClick={() => void handleDelete(row.id)} style={btnDanger}>Delete</button>`,
        `              </td>`,
        `            </tr>`,
        `          ))}`,
        `          {data.length === 0 && (`,
        `            <tr>`,
        `              <td colSpan={3} style={{ ...td, textAlign: "center", color: "#94a3b8" }}>No records yet.</td>`,
        `            </tr>`,
        `          )}`,
        `        </tbody>`,
        `      </table>`,
        ``,
        `      {(creating || editing !== null) && (`,
        `        <RecordFormModal`,
        `          record={editing}`,
        `          mutation={mutation}`,
        `          onClose={() => { setCreating(false); setEditing(null); }}`,
        `          onSaved={() => { setCreating(false); setEditing(null); refetch(); }}`,
        `        />`,
        `      )}`,
        `    </div>`,
        `  );`,
        `}`,
        ``,
        `const th: React.CSSProperties = { padding: "10px 12px", textAlign: "left", fontWeight: 600, fontSize: "0.875rem" };`,
        `const td: React.CSSProperties = { padding: "10px 12px", fontSize: "0.875rem" };`,
        `const btnSecondary: React.CSSProperties = { marginRight: "8px", padding: "4px 10px", background: "#e2e8f0", border: "none", borderRadius: "4px", cursor: "pointer" };`,
        `const btnDanger: React.CSSProperties    = { padding: "4px 10px", background: "#fee2e2", color: "#dc2626", border: "none", borderRadius: "4px", cursor: "pointer" };`,
      ].join("\n"),

      "/src/components/RecordFormModal.tsx": [
        `/**`,
        ` * RecordFormModal — create / edit form in an overlay dialog.`,
        ` *`,
        ` * Receives an optional Record (null = create mode, defined = edit mode).`,
        ` * Calls the mutation directly and delegates success/error handling to the parent.`,
        ` */`,
        `import React, { useState } from "react";`,
        `import type { Record } from "./RecordTable.js";`,
        `import type { MutationResult } from "@oneplatform/app-sdk";`,
        ``,
        `interface Props {`,
        `  record:    Record | null;`,
        `  mutation:  MutationResult<Record>;`,
        `  onClose(): void;`,
        `  onSaved(): void;`,
        `}`,
        ``,
        `export function RecordFormModal({ record, mutation, onClose, onSaved }: Props) {`,
        `  const [name,  setName]  = useState(record?.name  ?? "");`,
        `  const [value, setValue] = useState(record?.value ?? "");`,
        `  const [error, setError] = useState<string | null>(null);`,
        ``,
        `  async function handleSubmit(e: React.FormEvent): Promise<void> {`,
        `    e.preventDefault();`,
        `    if (name.trim() === "") { setError("Name is required."); return; }`,
        `    try {`,
        `      if (record !== null) {`,
        `        await mutation.update(record.id, { name: name.trim(), value: value.trim() });`,
        `      } else {`,
        `        await mutation.create({ name: name.trim(), value: value.trim() });`,
        `      }`,
        `      onSaved();`,
        `    } catch (err) {`,
        `      setError(err instanceof Error ? err.message : "Save failed.");`,
        `    }`,
        `  }`,
        ``,
        `  return (`,
        `    <div style={overlay}>`,
        `      <div style={modal}>`,
        `        <h2 style={{ marginBottom: "16px", fontSize: "1.125rem", fontWeight: 600 }}>`,
        `          {record !== null ? "Edit record" : "New record"}`,
        `        </h2>`,
        `        {error !== null && <p style={{ color: "red", marginBottom: "12px", fontSize: "0.875rem" }}>{error}</p>}`,
        `        <form onSubmit={(e) => void handleSubmit(e)}>`,
        `          <label style={labelStyle}>Name</label>`,
        `          <input value={name} onChange={(e) => setName(e.target.value)} style={inputStyle} placeholder="Name" />`,
        `          <label style={labelStyle}>Value</label>`,
        `          <input value={value} onChange={(e) => setValue(e.target.value)} style={inputStyle} placeholder="Value" />`,
        `          <div style={{ display: "flex", gap: "8px", marginTop: "16px" }}>`,
        `            <button type="submit" disabled={mutation.isLoading} style={btnPrimary}>`,
        `              {mutation.isLoading ? "Saving…" : "Save"}`,
        `            </button>`,
        `            <button type="button" onClick={onClose} style={btnCancel}>Cancel</button>`,
        `          </div>`,
        `        </form>`,
        `      </div>`,
        `    </div>`,
        `  );`,
        `}`,
        ``,
        `const overlay: React.CSSProperties  = { position: "fixed", inset: 0, background: "rgba(0,0,0,0.4)", display: "flex", alignItems: "center", justifyContent: "center", zIndex: 50 };`,
        `const modal: React.CSSProperties    = { background: "#fff", borderRadius: "8px", padding: "24px", width: "100%", maxWidth: "440px", boxShadow: "0 4px 24px rgba(0,0,0,0.15)" };`,
        `const labelStyle: React.CSSProperties = { display: "block", marginBottom: "4px", fontSize: "0.875rem", fontWeight: 500 };`,
        `const inputStyle: React.CSSProperties = { display: "block", width: "100%", marginBottom: "12px", padding: "8px 10px", border: "1px solid #cbd5e1", borderRadius: "6px", fontSize: "0.875rem", boxSizing: "border-box" };`,
        `const btnPrimary: React.CSSProperties  = { padding: "8px 18px", background: "#2563eb", color: "#fff", border: "none", borderRadius: "6px", cursor: "pointer", fontWeight: 600 };`,
        `const btnCancel: React.CSSProperties   = { padding: "8px 18px", background: "#f1f5f9", border: "none", borderRadius: "6px", cursor: "pointer" };`,
      ].join("\n"),
    };
  },
};
