// ---------------------------------------------------------------------------
// Analytics dashboard template — G-075
//
// Produces KPI summary cards and a simple bar-chart using SVG (no external
// charting library dependency). Data is driven by the app-sdk useQuery hook
// so it connects to real entities the moment the user wires up the entity name.
// ---------------------------------------------------------------------------

import type { AppTemplate } from "./types.js";

export const dashboardTemplate: AppTemplate = {
  meta: {
    id:          "dashboard",
    name:        "Analytics Dashboard",
    description: "KPI cards and a bar chart connected to your data. Ready to wire up to any entity.",
    category:    "dashboard",
    thumbnail:   "/assets/templates/dashboard.png",
    requiredPermissions: ["entity:read"],
  },

  render(appName: string, slug: string): Record<string, string> {
    return {
      "/package.json": JSON.stringify(
        {
          name:    slug,
          version: "0.1.0",
          dependencies: {
            react:             "^18.2.0",
            "react-dom":       "^18.2.0",
            "@oneplatform/app-sdk": "^1.0.0",
          },
        },
        null,
        2
      ),

      "/tsconfig.json": JSON.stringify(
        {
          compilerOptions: {
            target:                   "ES2022",
            module:                   "ESNext",
            moduleResolution:         "bundler",
            jsx:                      "react-jsx",
            strict:                   true,
            esModuleInterop:          true,
            allowSyntheticDefaultImports: true,
          },
          include: ["src"],
        },
        null,
        2
      ),

      "/src/index.tsx": [
        `import React from "react";`,
        `import { createRoot } from "react-dom/client";`,
        `import { AppProvider } from "@oneplatform/app-sdk";`,
        `import { App } from "./App.js";`,
        ``,
        `const container = document.getElementById("app");`,
        `if (!container) throw new Error("Root element #app not found");`,
        ``,
        `createRoot(container).render(`,
        `  <AppProvider>`,
        `    <App />`,
        `  </AppProvider>`,
        `);`,
      ].join("\n"),

      "/src/App.tsx": [
        `import React from "react";`,
        `import { KpiSection } from "./components/KpiSection.js";`,
        `import { BarChart } from "./components/BarChart.js";`,
        `import { useQuery } from "@oneplatform/app-sdk";`,
        ``,
        `/**`,
        ` * Replace "events" with your actual entity name and update the`,
        ` * derived fields in KpiSection / BarChart accordingly.`,
        ` */`,
        `interface Event {`,
        `  id:       string;`,
        `  type:     string;`,
        `  value:    number;`,
        `  date:     string;`,
        `}`,
        ``,
        `export function App() {`,
        `  const { data, isLoading, error } = useQuery<Event>("events");`,
        ``,
        `  if (isLoading) return <div style={containerStyle}><p>Loading…</p></div>;`,
        `  if (error)     return <div style={containerStyle}><p style={{ color: "red" }}>Error: {error.message}</p></div>;`,
        ``,
        `  const total  = data.reduce((s, e) => s + e.value, 0);`,
        `  const avg    = data.length > 0 ? total / data.length : 0;`,
        `  const recent = data.slice(-7);`,
        ``,
        `  const chartData = recent.map((e) => ({ label: e.date, value: e.value }));`,
        ``,
        `  return (`,
        `    <div style={containerStyle}>`,
        `      <h1 style={{ marginBottom: "24px", fontSize: "1.5rem", fontWeight: 700 }}>${appName}</h1>`,
        `      <KpiSection total={total} count={data.length} avg={avg} />`,
        `      <div style={{ marginTop: "32px" }}>`,
        `        <h2 style={{ fontSize: "1rem", fontWeight: 600, marginBottom: "16px" }}>Recent values (last 7)</h2>`,
        `        <BarChart data={chartData} />`,
        `      </div>`,
        `    </div>`,
        `  );`,
        `}`,
        ``,
        `const containerStyle: React.CSSProperties = { padding: "24px", fontFamily: "system-ui, sans-serif" };`,
      ].join("\n"),

      "/src/components/KpiSection.tsx": [
        `import React from "react";`,
        ``,
        `interface Props {`,
        `  total: number;`,
        `  count: number;`,
        `  avg:   number;`,
        `}`,
        ``,
        `export function KpiSection({ total, count, avg }: Props) {`,
        `  return (`,
        `    <div style={{ display: "grid", gridTemplateColumns: "repeat(3, 1fr)", gap: "16px" }}>`,
        `      <KpiCard label="Total value"  value={total.toLocaleString()} color="#2563eb" />`,
        `      <KpiCard label="Record count" value={count.toLocaleString()} color="#16a34a" />`,
        `      <KpiCard label="Average"      value={avg.toFixed(2)}         color="#9333ea" />`,
        `    </div>`,
        `  );`,
        `}`,
        ``,
        `function KpiCard({ label, value, color }: { label: string; value: string; color: string }) {`,
        `  return (`,
        `    <div style={{ background: "#f8fafc", borderRadius: "8px", padding: "20px", borderLeft: \`4px solid \${color}\` }}>`,
        `      <p style={{ fontSize: "0.75rem", color: "#64748b", marginBottom: "4px", textTransform: "uppercase", letterSpacing: "0.05em" }}>{label}</p>`,
        `      <p style={{ fontSize: "1.75rem", fontWeight: 700, color }}>{value}</p>`,
        `    </div>`,
        `  );`,
        `}`,
      ].join("\n"),

      "/src/components/BarChart.tsx": [
        `/**`,
        ` * BarChart — pure SVG bar chart with no external dependencies.`,
        ` *`,
        ` * Renders up to 20 data points. Each bar is labelled on the x-axis.`,
        ` * Intentionally minimal; replace with Recharts/Victory once you add them`,
        ` * to your package.json and rebuild.`,
        ` */`,
        `import React from "react";`,
        ``,
        `interface DataPoint {`,
        `  label: string;`,
        `  value: number;`,
        `}`,
        ``,
        `interface Props {`,
        `  data: DataPoint[];`,
        `}`,
        ``,
        `const WIDTH  = 600;`,
        `const HEIGHT = 240;`,
        `const PAD_L  = 40;`,
        `const PAD_B  = 40;`,
        `const CHART_W = WIDTH  - PAD_L - 8;`,
        `const CHART_H = HEIGHT - PAD_B - 8;`,
        ``,
        `export function BarChart({ data }: Props) {`,
        `  if (data.length === 0) {`,
        `    return <p style={{ color: "#94a3b8", fontSize: "0.875rem" }}>No chart data yet.</p>;`,
        `  }`,
        ``,
        `  const maxValue = Math.max(...data.map((d) => d.value), 1);`,
        `  const barWidth = (CHART_W / data.length) * 0.7;`,
        `  const gap      = CHART_W / data.length;`,
        ``,
        `  return (`,
        `    <svg`,
        `      viewBox={\`0 0 \${WIDTH} \${HEIGHT}\`}`,
        `      style={{ width: "100%", maxWidth: WIDTH, display: "block" }}`,
        `      role="img"`,
        `      aria-label="Bar chart"`,
        `    >`,
        `      {/* Y-axis */}`,
        `      <line x1={PAD_L} y1={8} x2={PAD_L} y2={HEIGHT - PAD_B} stroke="#cbd5e1" strokeWidth={1} />`,
        `      {/* X-axis */}`,
        `      <line x1={PAD_L} y1={HEIGHT - PAD_B} x2={WIDTH - 8} y2={HEIGHT - PAD_B} stroke="#cbd5e1" strokeWidth={1} />`,
        ``,
        `      {data.map((d, i) => {`,
        `        const barHeight = (d.value / maxValue) * CHART_H;`,
        `        const x = PAD_L + i * gap + (gap - barWidth) / 2;`,
        `        const y = HEIGHT - PAD_B - barHeight;`,
        `        return (`,
        `          <g key={i}>`,
        `            <rect x={x} y={y} width={barWidth} height={barHeight} fill="#2563eb" rx={3} />`,
        `            <text`,
        `              x={x + barWidth / 2}`,
        `              y={HEIGHT - PAD_B + 14}`,
        `              textAnchor="middle"`,
        `              fontSize={9}`,
        `              fill="#64748b"`,
        `            >`,
        `              {d.label.length > 8 ? d.label.slice(0, 8) + "…" : d.label}`,
        `            </text>`,
        `          </g>`,
        `        );`,
        `      })}`,
        `    </svg>`,
        `  );`,
        `}`,
      ].join("\n"),
    };
  },
};
