// ---------------------------------------------------------------------------
// Form submission app template — G-075
//
// Produces a validated multi-field form that stores submissions via the
// app-sdk useMutation hook. Client-side validation mirrors what users expect
// from a real form tool (required fields, email format, min length).
// ---------------------------------------------------------------------------

import type { AppTemplate } from "./types.js";

export const formBuilderTemplate: AppTemplate = {
  meta: {
    id:          "form-builder",
    name:        "Form Submission App",
    description: "Validated form that saves submissions to your data entity. Add, remove, or rename fields to match your schema.",
    category:    "form",
    thumbnail:   "/assets/templates/form-builder.png",
    requiredPermissions: ["entity:create"],
  },

  render(appName: string, slug: string): Record<string, string> {
    return {
      "/package.json": JSON.stringify(
        {
          name:    slug,
          version: "0.1.0",
          dependencies: {
            react:             "^18.2.0",
            "react-dom":       "^18.2.0",
            "@oneplatform/app-sdk": "^1.0.0",
          },
        },
        null,
        2
      ),

      "/tsconfig.json": JSON.stringify(
        {
          compilerOptions: {
            target:                   "ES2022",
            module:                   "ESNext",
            moduleResolution:         "bundler",
            jsx:                      "react-jsx",
            strict:                   true,
            esModuleInterop:          true,
            allowSyntheticDefaultImports: true,
          },
          include: ["src"],
        },
        null,
        2
      ),

      "/src/index.tsx": [
        `import React from "react";`,
        `import { createRoot } from "react-dom/client";`,
        `import { AppProvider } from "@oneplatform/app-sdk";`,
        `import { App } from "./App.js";`,
        ``,
        `const container = document.getElementById("app");`,
        `if (!container) throw new Error("Root element #app not found");`,
        ``,
        `createRoot(container).render(`,
        `  <AppProvider>`,
        `    <App />`,
        `  </AppProvider>`,
        `);`,
      ].join("\n"),

      "/src/App.tsx": [
        `import React from "react";`,
        `import { SubmissionForm } from "./components/SubmissionForm.js";`,
        ``,
        `export function App() {`,
        `  return (`,
        `    <div style={{ padding: "24px", fontFamily: "system-ui, sans-serif" }}>`,
        `      <h1 style={{ marginBottom: "8px", fontSize: "1.5rem", fontWeight: 700 }}>${appName}</h1>`,
        `      <p style={{ marginBottom: "32px", color: "#64748b", fontSize: "0.875rem" }}>`,
        `        Fill in the form below. All fields marked * are required.`,
        `      </p>`,
        `      <SubmissionForm />`,
        `    </div>`,
        `  );`,
        `}`,
      ].join("\n"),

      "/src/components/SubmissionForm.tsx": [
        `/**`,
        ` * SubmissionForm — validated form connected to the "submissions" entity.`,
        ` *`,
        ` * Rename the "submissions" entity key and the FormData fields to match`,
        ` * your actual data model. Validation runs before the SDK mutation fires.`,
        ` */`,
        `import React, { useState } from "react";`,
        `import { useMutation } from "@oneplatform/app-sdk";`,
        `import { validateForm, type FormErrors } from "../lib/validate.js";`,
        ``,
        `interface FormData {`,
        `  fullName: string;`,
        `  email:    string;`,
        `  message:  string;`,
        `}`,
        ``,
        `const EMPTY: FormData = { fullName: "", email: "", message: "" };`,
        ``,
        `export function SubmissionForm() {`,
        `  const mutation = useMutation<FormData>("submissions");`,
        ``,
        `  const [form,    setForm]    = useState<FormData>(EMPTY);`,
        `  const [errors,  setErrors]  = useState<FormErrors>({});`,
        `  const [success, setSuccess] = useState(false);`,
        ``,
        `  function handleChange(field: keyof FormData, value: string): void {`,
        `    setForm((prev) => ({ ...prev, [field]: value }));`,
        `    // Clear per-field error as the user corrects it`,
        `    if (errors[field] !== undefined) {`,
        `      setErrors((prev) => { const next = { ...prev }; delete next[field]; return next; });`,
        `    }`,
        `  }`,
        ``,
        `  async function handleSubmit(e: React.FormEvent): Promise<void> {`,
        `    e.preventDefault();`,
        `    const fieldErrors = validateForm(form);`,
        `    if (Object.keys(fieldErrors).length > 0) {`,
        `      setErrors(fieldErrors);`,
        `      return;`,
        `    }`,
        `    try {`,
        `      await mutation.create(form);`,
        `      setSuccess(true);`,
        `      setForm(EMPTY);`,
        `      setErrors({});`,
        `    } catch (err) {`,
        `      setErrors({ _form: err instanceof Error ? err.message : "Submission failed." });`,
        `    }`,
        `  }`,
        ``,
        `  if (success) {`,
        `    return (`,
        `      <div style={{ padding: "24px", background: "#f0fdf4", borderRadius: "8px", border: "1px solid #86efac" }}>`,
        `        <p style={{ color: "#15803d", fontWeight: 600 }}>Thank you — your submission was received!</p>`,
        `        <button onClick={() => setSuccess(false)} style={btnSecondary}>Submit another</button>`,
        `      </div>`,
        `    );`,
        `  }`,
        ``,
        `  return (`,
        `    <form onSubmit={(e) => void handleSubmit(e)} style={{ maxWidth: "520px" }} noValidate>`,
        `      {errors["_form"] !== undefined && (`,
        `        <p style={{ color: "red", marginBottom: "16px", fontSize: "0.875rem" }}>{errors["_form"]}</p>`,
        `      )}`,
        ``,
        `      <Field`,
        `        id="fullName" label="Full name *" type="text"`,
        `        value={form.fullName} error={errors["fullName"]}`,
        `        onChange={(v) => handleChange("fullName", v)}`,
        `      />`,
        `      <Field`,
        `        id="email" label="Email address *" type="email"`,
        `        value={form.email} error={errors["email"]}`,
        `        onChange={(v) => handleChange("email", v)}`,
        `      />`,
        ``,
        `      <div style={{ marginBottom: "20px" }}>`,
        `        <label htmlFor="message" style={labelStyle}>Message *</label>`,
        `        <textarea`,
        `          id="message"`,
        `          value={form.message}`,
        `          onChange={(e) => handleChange("message", e.target.value)}`,
        `          rows={5}`,
        `          style={{ ...inputStyle, resize: "vertical" }}`,
        `          aria-invalid={errors["message"] !== undefined}`,
        `          aria-describedby={errors["message"] !== undefined ? "err-message" : undefined}`,
        `        />`,
        `        {errors["message"] !== undefined && (`,
        `          <span id="err-message" style={errorStyle}>{errors["message"]}</span>`,
        `        )}`,
        `      </div>`,
        ``,
        `      <button type="submit" disabled={mutation.isLoading} style={btnPrimary}>`,
        `        {mutation.isLoading ? "Submitting…" : "Submit"}`,
        `      </button>`,
        `    </form>`,
        `  );`,
        `}`,
        ``,
        `interface FieldProps {`,
        `  id:       string;`,
        `  label:    string;`,
        `  type:     string;`,
        `  value:    string;`,
        `  error?:   string;`,
        `  onChange(v: string): void;`,
        `}`,
        ``,
        `function Field({ id, label, type, value, error, onChange }: FieldProps) {`,
        `  const errId = \`err-\${id}\`;`,
        `  return (`,
        `    <div style={{ marginBottom: "20px" }}>`,
        `      <label htmlFor={id} style={labelStyle}>{label}</label>`,
        `      <input`,
        `        id={id}`,
        `        type={type}`,
        `        value={value}`,
        `        onChange={(e) => onChange(e.target.value)}`,
        `        style={inputStyle}`,
        `        aria-invalid={error !== undefined}`,
        `        aria-describedby={error !== undefined ? errId : undefined}`,
        `      />`,
        `      {error !== undefined && <span id={errId} style={errorStyle}>{error}</span>}`,
        `    </div>`,
        `  );`,
        `}`,
        ``,
        `const labelStyle: React.CSSProperties  = { display: "block", marginBottom: "6px", fontSize: "0.875rem", fontWeight: 500 };`,
        `const inputStyle: React.CSSProperties  = { display: "block", width: "100%", padding: "8px 10px", border: "1px solid #cbd5e1", borderRadius: "6px", fontSize: "0.875rem", boxSizing: "border-box" };`,
        `const errorStyle: React.CSSProperties  = { display: "block", marginTop: "4px", color: "#dc2626", fontSize: "0.75rem" };`,
        `const btnPrimary: React.CSSProperties  = { padding: "10px 20px", background: "#2563eb", color: "#fff", border: "none", borderRadius: "6px", cursor: "pointer", fontWeight: 600, fontSize: "0.875rem" };`,
        `const btnSecondary: React.CSSProperties = { marginTop: "12px", padding: "8px 16px", background: "#e2e8f0", border: "none", borderRadius: "6px", cursor: "pointer" };`,
      ].join("\n"),

      "/src/lib/validate.ts": [
        `// Client-side validation rules for the submission form.`,
        `// Keeps validation logic separate from the form component so it can be`,
        `// unit-tested without rendering.`,
        ``,
        `export type FormErrors = Record<string, string>;`,
        ``,
        `interface SubmissionValues {`,
        `  fullName: string;`,
        `  email:    string;`,
        `  message:  string;`,
        `}`,
        ``,
        `const EMAIL_RE = /^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$/;`,
        ``,
        `export function validateForm(values: SubmissionValues): FormErrors {`,
        `  const errors: FormErrors = {};`,
        ``,
        `  if (values.fullName.trim().length === 0) {`,
        `    errors["fullName"] = "Full name is required.";`,
        `  } else if (values.fullName.trim().length < 2) {`,
        `    errors["fullName"] = "Full name must be at least 2 characters.";`,
        `  }`,
        ``,
        `  if (values.email.trim().length === 0) {`,
        `    errors["email"] = "Email address is required.";`,
        `  } else if (!EMAIL_RE.test(values.email.trim())) {`,
        `    errors["email"] = "Please enter a valid email address.";`,
        `  }`,
        ``,
        `  if (values.message.trim().length === 0) {`,
        `    errors["message"] = "Message is required.";`,
        `  } else if (values.message.trim().length < 10) {`,
        `    errors["message"] = "Message must be at least 10 characters.";`,
        `  }`,
        ``,
        `  return errors;`,
        `}`,
      ].join("\n"),
    };
  },
};
