// ---------------------------------------------------------------------------
// Project Tracker template — G-075 / NCD-002
//
// Produces a filter bar (status selector) + data table with status badges
// + quick-add form. Connects to any "projects" or "tasks" entity.
// ---------------------------------------------------------------------------

import type { AppTemplate } from "./types.js";
import { escapeForTemplateLiteral } from "./escape.js";

export const projectTrackerTemplate: AppTemplate = {
  meta: {
    id:          "project-tracker",
    name:        "Project Tracker",
    description: "Filter bar, status-badged data table, and quick-add form for projects or tasks.",
    category:    "admin",
    thumbnail:   "/assets/templates/project-tracker.png",
    requiredPermissions: ["entity:read", "entity:create"],
  },

  render(appName: string, slug: string): Record<string, string> {
    const safeName = escapeForTemplateLiteral(appName);
    return {
      "/package.json": JSON.stringify(
        {
          name: slug,
          version: "0.1.0",
          dependencies: {
            react: "^18.2.0",
            "react-dom": "^18.2.0",
            "@oneplatform/app-sdk": "^1.0.0",
          },
        },
        null,
        2
      ),

      "/tsconfig.json": JSON.stringify(
        {
          compilerOptions: {
            target: "ES2022",
            module: "ESNext",
            moduleResolution: "bundler",
            jsx: "react-jsx",
            strict: true,
            esModuleInterop: true,
            allowSyntheticDefaultImports: true,
          },
          include: ["src"],
        },
        null,
        2
      ),

      "/src/index.tsx": [
        `import React from "react";`,
        `import { createRoot } from "react-dom/client";`,
        `import { AppProvider } from "@oneplatform/app-sdk";`,
        `import { App } from "./App.js";`,
        ``,
        `const container = document.getElementById("app");`,
        `if (!container) throw new Error("Root element #app not found");`,
        `createRoot(container).render(<AppProvider><App /></AppProvider>);`,
      ].join("\n"),

      "/src/App.tsx": [
        `/**`,
        ` * Replace "projects" with your entity name.`,
        ` * Expected fields: id, title, status (todo|in-progress|done|blocked),`,
        ` * owner (string), dueDate (string | null), priority (string).`,
        ` */`,
        `import React, { useState } from "react";`,
        `import { useQuery, useMutation } from "@oneplatform/app-sdk";`,
        `import { ProjectTable } from "./components/ProjectTable.js";`,
        `import { QuickAdd } from "./components/QuickAdd.js";`,
        ``,
        `export type Status = "todo" | "in-progress" | "done" | "blocked";`,
        ``,
        `export interface Project {`,
        `  id:        string;`,
        `  title:     string;`,
        `  status:    Status;`,
        `  owner:     string;`,
        `  dueDate:   string | null;`,
        `  priority:  string;`,
        `}`,
        ``,
        `const ALL_STATUSES: Array<Status | "all"> = ["all", "todo", "in-progress", "done", "blocked"];`,
        ``,
        `export function App() {`,
        `  const [statusFilter, setStatusFilter] = useState<Status | "all">("all");`,
        `  const { data, isLoading, error, refetch } = useQuery<Project>("projects");`,
        `  const mutation = useMutation<Project>("projects");`,
        ``,
        `  if (isLoading) return <div style={wrap}><p>Loading projects…</p></div>;`,
        `  if (error)     return <div style={wrap}><p style={{ color: "red" }}>Error: {error.message}</p></div>;`,
        ``,
        `  const filtered = statusFilter === "all" ? data : data.filter((p) => p.status === statusFilter);`,
        ``,
        `  async function handleAdd(title: string): Promise<void> {`,
        `    await mutation.create({ title, status: "todo", owner: "", dueDate: null, priority: "medium" });`,
        `    refetch();`,
        `  }`,
        ``,
        `  return (`,
        `    <div style={wrap}>`,
        `      <h1 style={{ fontSize: "1.5rem", fontWeight: 700, marginBottom: "20px" }}>${safeName}</h1>`,
        ``,
        `      {/* Filter bar */}`,
        `      <div style={{ display: "flex", gap: "8px", marginBottom: "16px", flexWrap: "wrap" }}>`,
        `        {ALL_STATUSES.map((s) => (`,
        `          <button`,
        `            key={s}`,
        `            onClick={() => setStatusFilter(s as Status | "all")}`,
        `            style={{`,
        `              padding: "6px 14px",`,
        `              borderRadius: "9999px",`,
        `              border: "1px solid",`,
        `              fontSize: "0.8125rem",`,
        `              fontWeight: statusFilter === s ? 600 : 400,`,
        `              cursor: "pointer",`,
        `              background: statusFilter === s ? "#2563eb" : "#fff",`,
        `              color: statusFilter === s ? "#fff" : "#374151",`,
        `              borderColor: statusFilter === s ? "#2563eb" : "#d1d5db",`,
        `            }}`,
        `          >`,
        `            {s === "all" ? "All" : s.replace("-", " ")}`,
        `          </button>`,
        `        ))}`,
        `      </div>`,
        ``,
        `      <QuickAdd onAdd={(title) => void handleAdd(title)} isLoading={mutation.isLoading} />`,
        `      <div style={{ marginTop: "16px" }}>`,
        `        <ProjectTable projects={filtered} />`,
        `      </div>`,
        `    </div>`,
        `  );`,
        `}`,
        ``,
        `const wrap = { padding: "24px", fontFamily: "system-ui, sans-serif" };`,
      ].join("\n"),

      "/src/components/ProjectTable.tsx": [
        `import React from "react";`,
        `import type { Project, Status } from "../App.js";`,
        ``,
        `const STATUS_STYLE: Record<Status, React.CSSProperties> = {`,
        `  "todo":        { background: "#f1f5f9", color: "#475569" },`,
        `  "in-progress": { background: "#dbeafe", color: "#1d4ed8" },`,
        `  "done":        { background: "#dcfce7", color: "#15803d" },`,
        `  "blocked":     { background: "#fee2e2", color: "#dc2626" },`,
        `};`,
        ``,
        `export function ProjectTable({ projects }: { projects: Project[] }) {`,
        `  return (`,
        `    <table style={{ width: "100%", borderCollapse: "collapse", fontSize: "0.875rem" }}>`,
        `      <thead>`,
        `        <tr style={{ background: "#f8fafc" }}>`,
        `          <th style={th}>Project</th>`,
        `          <th style={th}>Status</th>`,
        `          <th style={th}>Owner</th>`,
        `          <th style={th}>Priority</th>`,
        `          <th style={th}>Due</th>`,
        `        </tr>`,
        `      </thead>`,
        `      <tbody>`,
        `        {projects.map((p) => (`,
        `          <tr key={p.id} style={{ borderBottom: "1px solid #e2e8f0" }}>`,
        `            <td style={{ ...td, fontWeight: 500 }}>{p.title}</td>`,
        `            <td style={td}>`,
        `              <span style={{ ...badge, ...STATUS_STYLE[p.status] }}>`,
        `                {p.status.replace("-", " ")}`,
        `              </span>`,
        `            </td>`,
        `            <td style={td}>{p.owner || "—"}</td>`,
        `            <td style={td}>{p.priority}</td>`,
        `            <td style={td}>{p.dueDate ?? "—"}</td>`,
        `          </tr>`,
        `        ))}`,
        `        {projects.length === 0 && (`,
        `          <tr><td colSpan={5} style={{ ...td, textAlign: "center", color: "#94a3b8" }}>No projects match this filter.</td></tr>`,
        `        )}`,
        `      </tbody>`,
        `    </table>`,
        `  );`,
        `}`,
        ``,
        `const th:    React.CSSProperties = { padding: "10px 12px", textAlign: "left", fontWeight: 600 };`,
        `const td:    React.CSSProperties = { padding: "10px 12px" };`,
        `const badge: React.CSSProperties = { display: "inline-block", padding: "2px 8px", borderRadius: "9999px", fontSize: "0.75rem", fontWeight: 500, textTransform: "capitalize" };`,
      ].join("\n"),

      "/src/components/QuickAdd.tsx": [
        `import React, { useState } from "react";`,
        ``,
        `interface Props { onAdd(title: string): void; isLoading: boolean; }`,
        ``,
        `export function QuickAdd({ onAdd, isLoading }: Props) {`,
        `  const [title, setTitle] = useState("");`,
        ``,
        `  function handleSubmit(e: React.FormEvent): void {`,
        `    e.preventDefault();`,
        `    if (title.trim() === "") return;`,
        `    onAdd(title.trim());`,
        `    setTitle("");`,
        `  }`,
        ``,
        `  return (`,
        `    <form onSubmit={handleSubmit} style={{ display: "flex", gap: "8px" }}>`,
        `      <input`,
        `        type="text"`,
        `        placeholder="Quick-add a project…"`,
        `        value={title}`,
        `        onChange={(e) => setTitle(e.target.value)}`,
        `        style={{ flex: 1, maxWidth: "360px", padding: "8px 12px", border: "1px solid #cbd5e1", borderRadius: "6px", fontSize: "0.875rem" }}`,
        `      />`,
        `      <button`,
        `        type="submit"`,
        `        disabled={isLoading || title.trim() === ""}`,
        `        style={{ padding: "8px 16px", background: "#2563eb", color: "#fff", border: "none", borderRadius: "6px", cursor: "pointer", fontWeight: 600, fontSize: "0.875rem" }}`,
        `      >`,
        `        {isLoading ? "Adding…" : "Add"}`,
        `      </button>`,
        `    </form>`,
        `  );`,
        `}`,
      ].join("\n"),
    };
  },
};
