// ---------------------------------------------------------------------------
// Sales Dashboard template — G-075 / NCD-002
//
// Produces KPI cards (revenue, deals, avg deal size, win rate), a bar chart
// of revenue by period, and a deals data table. Data is driven by the
// app-sdk useQuery hook — wire up to any "deals" or "sales" entity.
// ---------------------------------------------------------------------------

import type { AppTemplate } from "./types.js";
import { escapeForTemplateLiteral } from "./escape.js";

export const salesDashboardTemplate: AppTemplate = {
  meta: {
    id:          "sales-dashboard",
    name:        "Sales Dashboard",
    description: "KPI cards, bar chart, and deals data table. Connect to your sales entity to track revenue and pipeline.",
    category:    "dashboard",
    thumbnail:   "/assets/templates/sales-dashboard.png",
    requiredPermissions: ["entity:read"],
  },

  render(appName: string, slug: string): Record<string, string> {
    const safeName = escapeForTemplateLiteral(appName);
    return {
      "/package.json": JSON.stringify(
        {
          name:    slug,
          version: "0.1.0",
          dependencies: {
            react:                  "^18.2.0",
            "react-dom":            "^18.2.0",
            "@oneplatform/app-sdk": "^1.0.0",
          },
        },
        null,
        2
      ),

      "/tsconfig.json": JSON.stringify(
        {
          compilerOptions: {
            target:                       "ES2022",
            module:                       "ESNext",
            moduleResolution:             "bundler",
            jsx:                          "react-jsx",
            strict:                       true,
            esModuleInterop:              true,
            allowSyntheticDefaultImports: true,
          },
          include: ["src"],
        },
        null,
        2
      ),

      "/src/index.tsx": [
        `import React from "react";`,
        `import { createRoot } from "react-dom/client";`,
        `import { AppProvider } from "@oneplatform/app-sdk";`,
        `import { App } from "./App.js";`,
        ``,
        `const container = document.getElementById("app");`,
        `if (!container) throw new Error("Root element #app not found");`,
        ``,
        `createRoot(container).render(`,
        `  <AppProvider>`,
        `    <App />`,
        `  </AppProvider>`,
        `);`,
      ].join("\n"),

      "/src/App.tsx": [
        `/**`,
        ` * Replace "deals" with your actual sales entity name.`,
        ` * Expected fields: id, title, amount (number), stage (string), closedAt (string | null).`,
        ` */`,
        `import React from "react";`,
        `import { useQuery } from "@oneplatform/app-sdk";`,
        `import { KpiGrid } from "./components/KpiGrid.js";`,
        `import { RevenueChart } from "./components/RevenueChart.js";`,
        `import { DealsTable } from "./components/DealsTable.js";`,
        ``,
        `export interface Deal {`,
        `  id:       string;`,
        `  title:    string;`,
        `  amount:   number;`,
        `  stage:    string;`,
        `  closedAt: string | null;`,
        `}`,
        ``,
        `export function App() {`,
        `  const { data, isLoading, error } = useQuery<Deal>("deals");`,
        ``,
        `  if (isLoading) return <div style={wrap}><p>Loading sales data…</p></div>;`,
        `  if (error)     return <div style={wrap}><p style={{ color: "red" }}>Error: {error.message}</p></div>;`,
        ``,
        `  const won       = data.filter((d) => d.stage === "won");`,
        `  const revenue   = won.reduce((s, d) => s + d.amount, 0);`,
        `  const avgDeal   = won.length > 0 ? revenue / won.length : 0;`,
        `  const winRate   = data.length > 0 ? (won.length / data.length) * 100 : 0;`,
        ``,
        `  // Aggregate revenue by month for the bar chart`,
        `  const byMonth: Record<string, number> = {};`,
        `  won.forEach((d) => {`,
        `    if (d.closedAt === null) return;`,
        `    const month = d.closedAt.slice(0, 7); // YYYY-MM`,
        `    byMonth[month] = (byMonth[month] ?? 0) + d.amount;`,
        `  });`,
        `  const chartData = Object.entries(byMonth)`,
        `    .sort(([a], [b]) => a.localeCompare(b))`,
        `    .slice(-6)`,
        `    .map(([label, value]) => ({ label, value }));`,
        ``,
        `  return (`,
        `    <div style={wrap}>`,
        `      <h1 style={heading}>${safeName}</h1>`,
        `      <KpiGrid revenue={revenue} deals={data.length} avgDeal={avgDeal} winRate={winRate} />`,
        `      <h2 style={subheading}>Revenue by month</h2>`,
        `      <RevenueChart data={chartData} />`,
        `      <h2 style={subheading}>All deals</h2>`,
        `      <DealsTable deals={data} />`,
        `    </div>`,
        `  );`,
        `}`,
        ``,
        `const wrap      = { padding: "24px", fontFamily: "system-ui, sans-serif" };`,
        `const heading   = { fontSize: "1.5rem", fontWeight: 700, marginBottom: "24px" };`,
        `const subheading = { fontSize: "1rem", fontWeight: 600, margin: "32px 0 12px" };`,
      ].join("\n"),

      "/src/components/KpiGrid.tsx": [
        `import React from "react";`,
        ``,
        `interface Props {`,
        `  revenue:  number;`,
        `  deals:    number;`,
        `  avgDeal:  number;`,
        `  winRate:  number;`,
        `}`,
        ``,
        `export function KpiGrid({ revenue, deals, avgDeal, winRate }: Props) {`,
        `  return (`,
        `    <div style={{ display: "grid", gridTemplateColumns: "repeat(4, 1fr)", gap: "16px" }}>`,
        `      <Card label="Total revenue"   value={\`$\${revenue.toLocaleString()}\`}  color="#2563eb" />`,
        `      <Card label="Total deals"     value={deals.toLocaleString()}           color="#16a34a" />`,
        `      <Card label="Avg deal size"   value={\`$\${Math.round(avgDeal).toLocaleString()}\`} color="#9333ea" />`,
        `      <Card label="Win rate"        value={\`\${winRate.toFixed(1)}%\`}         color="#ea580c" />`,
        `    </div>`,
        `  );`,
        `}`,
        ``,
        `function Card({ label, value, color }: { label: string; value: string; color: string }) {`,
        `  return (`,
        `    <div style={{ background: "#f8fafc", borderRadius: "8px", padding: "20px", borderLeft: \`4px solid \${color}\` }}>`,
        `      <p style={{ fontSize: "0.75rem", color: "#64748b", textTransform: "uppercase", letterSpacing: "0.05em", marginBottom: "4px" }}>{label}</p>`,
        `      <p style={{ fontSize: "1.75rem", fontWeight: 700, color }}>{value}</p>`,
        `    </div>`,
        `  );`,
        `}`,
      ].join("\n"),

      "/src/components/RevenueChart.tsx": [
        `import React from "react";`,
        ``,
        `interface DataPoint { label: string; value: number; }`,
        ``,
        `const W = 600, H = 240, PL = 50, PB = 36, CW = W - PL - 8, CH = H - PB - 8;`,
        ``,
        `export function RevenueChart({ data }: { data: DataPoint[] }) {`,
        `  if (data.length === 0) return <p style={{ color: "#94a3b8", fontSize: "0.875rem" }}>No closed deals yet.</p>;`,
        `  const max = Math.max(...data.map((d) => d.value), 1);`,
        `  const bw  = (CW / data.length) * 0.7;`,
        `  const gap = CW / data.length;`,
        `  return (`,
        `    <svg viewBox={\`0 0 \${W} \${H}\`} style={{ width: "100%", maxWidth: W, display: "block" }} role="img" aria-label="Revenue bar chart">`,
        `      <line x1={PL} y1={8} x2={PL} y2={H - PB} stroke="#cbd5e1" strokeWidth={1} />`,
        `      <line x1={PL} y1={H - PB} x2={W - 8} y2={H - PB} stroke="#cbd5e1" strokeWidth={1} />`,
        `      {data.map((d, i) => {`,
        `        const bh = (d.value / max) * CH;`,
        `        const x  = PL + i * gap + (gap - bw) / 2;`,
        `        const y  = H - PB - bh;`,
        `        return (`,
        `          <g key={i}>`,
        `            <rect x={x} y={y} width={bw} height={bh} fill="#2563eb" rx={3} />`,
        `            <text x={x + bw / 2} y={H - PB + 14} textAnchor="middle" fontSize={9} fill="#64748b">`,
        `              {d.label}`,
        `            </text>`,
        `          </g>`,
        `        );`,
        `      })}`,
        `    </svg>`,
        `  );`,
        `}`,
      ].join("\n"),

      "/src/components/DealsTable.tsx": [
        `import React from "react";`,
        `import type { Deal } from "../App.js";`,
        ``,
        `const STAGE_COLOR: Record<string, string> = {`,
        `  won:      "#16a34a",`,
        `  lost:     "#dc2626",`,
        `  prospect: "#ea580c",`,
        `  proposal: "#2563eb",`,
        `};`,
        ``,
        `export function DealsTable({ deals }: { deals: Deal[] }) {`,
        `  return (`,
        `    <div style={{ overflowX: "auto" }}>`,
        `      <table style={{ width: "100%", borderCollapse: "collapse", fontSize: "0.875rem" }}>`,
        `        <thead>`,
        `          <tr style={{ background: "#f1f5f9" }}>`,
        `            <th style={th}>Deal</th>`,
        `            <th style={{ ...th, textAlign: "right" }}>Amount</th>`,
        `            <th style={th}>Stage</th>`,
        `            <th style={th}>Closed</th>`,
        `          </tr>`,
        `        </thead>`,
        `        <tbody>`,
        `          {deals.map((d) => (`,
        `            <tr key={d.id} style={{ borderBottom: "1px solid #e2e8f0" }}>`,
        `              <td style={td}>{d.title}</td>`,
        `              <td style={{ ...td, textAlign: "right" }}>\${d.amount.toLocaleString()}</td>`,
        `              <td style={td}>`,
        `                <span style={{ color: STAGE_COLOR[d.stage] ?? "#64748b", fontWeight: 500 }}>{d.stage}</span>`,
        `              </td>`,
        `              <td style={td}>{d.closedAt ?? "—"}</td>`,
        `            </tr>`,
        `          ))}`,
        `          {deals.length === 0 && (`,
        `            <tr><td colSpan={4} style={{ ...td, textAlign: "center", color: "#94a3b8" }}>No deals yet.</td></tr>`,
        `          )}`,
        `        </tbody>`,
        `      </table>`,
        `    </div>`,
        `  );`,
        `}`,
        ``,
        `const th: React.CSSProperties = { padding: "10px 12px", textAlign: "left", fontWeight: 600 };`,
        `const td: React.CSSProperties = { padding: "10px 12px" };`,
      ].join("\n"),
    };
  },
};
