// ---------------------------------------------------------------------------
// Support Metrics template — G-075 / NCD-002
//
// Produces stat cards (open tickets, resolved, avg response time, CSAT),
// a line chart of ticket volume over time, and a filter bar.
// ---------------------------------------------------------------------------

import type { AppTemplate } from "./types.js";

export const supportMetricsTemplate: AppTemplate = {
  meta: {
    id:          "support-metrics",
    name:        "Support Metrics",
    description: "Stat cards, ticket volume line chart, and filter bar for your support entity.",
    category:    "dashboard",
    thumbnail:   "/assets/templates/support-metrics.png",
    requiredPermissions: ["entity:read"],
  },

  render(appName: string, slug: string): Record<string, string> {
    return {
      "/package.json": JSON.stringify(
        {
          name: slug,
          version: "0.1.0",
          dependencies: {
            react: "^18.2.0",
            "react-dom": "^18.2.0",
            "@oneplatform/app-sdk": "^1.0.0",
          },
        },
        null,
        2
      ),

      "/tsconfig.json": JSON.stringify(
        {
          compilerOptions: {
            target: "ES2022",
            module: "ESNext",
            moduleResolution: "bundler",
            jsx: "react-jsx",
            strict: true,
            esModuleInterop: true,
            allowSyntheticDefaultImports: true,
          },
          include: ["src"],
        },
        null,
        2
      ),

      "/src/index.tsx": [
        `import React from "react";`,
        `import { createRoot } from "react-dom/client";`,
        `import { AppProvider } from "@oneplatform/app-sdk";`,
        `import { App } from "./App.js";`,
        ``,
        `const container = document.getElementById("app");`,
        `if (!container) throw new Error("Root element #app not found");`,
        `createRoot(container).render(<AppProvider><App /></AppProvider>);`,
      ].join("\n"),

      "/src/App.tsx": [
        `/**`,
        ` * Replace "tickets" with your actual support entity.`,
        ` * Expected fields: id, status (open|resolved|pending), priority (string),`,
        ` * responseTimeMinutes (number), csatScore (number | null), createdAt (string).`,
        ` */`,
        `import React, { useState } from "react";`,
        `import { useQuery } from "@oneplatform/app-sdk";`,
        `import { StatCards } from "./components/StatCards.js";`,
        `import { VolumeChart } from "./components/VolumeChart.js";`,
        ``,
        `export interface Ticket {`,
        `  id:                    string;`,
        `  status:                "open" | "resolved" | "pending";`,
        `  priority:              string;`,
        `  responseTimeMinutes:   number;`,
        `  csatScore:             number | null;`,
        `  createdAt:             string;`,
        `}`,
        ``,
        `export function App() {`,
        `  const [priorityFilter, setPriorityFilter] = useState<string>("all");`,
        `  const { data, isLoading, error } = useQuery<Ticket>("tickets");`,
        ``,
        `  if (isLoading) return <div style={wrap}><p>Loading support data…</p></div>;`,
        `  if (error)     return <div style={wrap}><p style={{ color: "red" }}>Error: {error.message}</p></div>;`,
        ``,
        `  const filtered = priorityFilter === "all" ? data : data.filter((t) => t.priority === priorityFilter);`,
        `  const open     = filtered.filter((t) => t.status === "open").length;`,
        `  const resolved = filtered.filter((t) => t.status === "resolved").length;`,
        `  const avgResp  = filtered.length > 0`,
        `    ? filtered.reduce((s, t) => s + t.responseTimeMinutes, 0) / filtered.length`,
        `    : 0;`,
        `  const csatArr  = filtered.map((t) => t.csatScore).filter((s): s is number => s !== null);`,
        `  const avgCsat  = csatArr.length > 0 ? csatArr.reduce((s, v) => s + v, 0) / csatArr.length : 0;`,
        ``,
        `  // Aggregate daily ticket volume`,
        `  const byDay: Record<string, number> = {};`,
        `  filtered.forEach((t) => {`,
        `    const day = t.createdAt.slice(0, 10);`,
        `    byDay[day] = (byDay[day] ?? 0) + 1;`,
        `  });`,
        `  const chartData = Object.entries(byDay)`,
        `    .sort(([a], [b]) => a.localeCompare(b))`,
        `    .slice(-14)`,
        `    .map(([label, value]) => ({ label, value }));`,
        ``,
        `  const priorities = ["all", ...Array.from(new Set(data.map((t) => t.priority)))];`,
        ``,
        `  return (`,
        `    <div style={wrap}>`,
        `      <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: "24px" }}>`,
        `        <h1 style={{ fontSize: "1.5rem", fontWeight: 700 }}>${appName}</h1>`,
        `        <div style={{ display: "flex", gap: "8px", alignItems: "center" }}>`,
        `          <label htmlFor="priority-filter" style={{ fontSize: "0.875rem", color: "#64748b" }}>Priority:</label>`,
        `          <select`,
        `            id="priority-filter"`,
        `            value={priorityFilter}`,
        `            onChange={(e) => setPriorityFilter(e.target.value)}`,
        `            style={{ padding: "6px 10px", borderRadius: "6px", border: "1px solid #cbd5e1", fontSize: "0.875rem" }}`,
        `          >`,
        `            {priorities.map((p) => <option key={p} value={p}>{p === "all" ? "All priorities" : p}</option>)}`,
        `          </select>`,
        `        </div>`,
        `      </div>`,
        `      <StatCards open={open} resolved={resolved} avgResp={avgResp} avgCsat={avgCsat} />`,
        `      <h2 style={{ fontSize: "1rem", fontWeight: 600, margin: "32px 0 12px" }}>Ticket volume (last 14 days)</h2>`,
        `      <VolumeChart data={chartData} />`,
        `    </div>`,
        `  );`,
        `}`,
        ``,
        `const wrap = { padding: "24px", fontFamily: "system-ui, sans-serif" };`,
      ].join("\n"),

      "/src/components/StatCards.tsx": [
        `import React from "react";`,
        ``,
        `interface Props { open: number; resolved: number; avgResp: number; avgCsat: number; }`,
        ``,
        `export function StatCards({ open, resolved, avgResp, avgCsat }: Props) {`,
        `  return (`,
        `    <div style={{ display: "grid", gridTemplateColumns: "repeat(4, 1fr)", gap: "16px" }}>`,
        `      <Card label="Open tickets"       value={String(open)}                   color="#ea580c" />`,
        `      <Card label="Resolved"           value={String(resolved)}               color="#16a34a" />`,
        `      <Card label="Avg response (min)" value={Math.round(avgResp).toString()} color="#2563eb" />`,
        `      <Card label="Avg CSAT"           value={avgCsat.toFixed(1) + " / 5"}   color="#9333ea" />`,
        `    </div>`,
        `  );`,
        `}`,
        ``,
        `function Card({ label, value, color }: { label: string; value: string; color: string }) {`,
        `  return (`,
        `    <div style={{ background: "#f8fafc", borderRadius: "8px", padding: "20px", borderLeft: \`4px solid \${color}\` }}>`,
        `      <p style={{ fontSize: "0.75rem", color: "#64748b", textTransform: "uppercase", letterSpacing: "0.05em", marginBottom: "4px" }}>{label}</p>`,
        `      <p style={{ fontSize: "1.75rem", fontWeight: 700, color }}>{value}</p>`,
        `    </div>`,
        `  );`,
        `}`,
      ].join("\n"),

      "/src/components/VolumeChart.tsx": [
        `import React from "react";`,
        ``,
        `interface DataPoint { label: string; value: number; }`,
        ``,
        `// Simple SVG polyline chart — no external library required`,
        `const W = 600, H = 200, PL = 40, PB = 30, CW = W - PL - 8, CH = H - PB - 8;`,
        ``,
        `export function VolumeChart({ data }: { data: DataPoint[] }) {`,
        `  if (data.length < 2) return <p style={{ color: "#94a3b8", fontSize: "0.875rem" }}>Not enough data for chart.</p>;`,
        `  const max = Math.max(...data.map((d) => d.value), 1);`,
        `  const points = data.map((d, i) => {`,
        `    const x = PL + (i / (data.length - 1)) * CW;`,
        `    const y = H - PB - (d.value / max) * CH;`,
        `    return \`\${x},\${y}\`;`,
        `  }).join(" ");`,
        `  return (`,
        `    <svg viewBox={\`0 0 \${W} \${H}\`} style={{ width: "100%", maxWidth: W, display: "block" }} role="img" aria-label="Ticket volume line chart">`,
        `      <line x1={PL} y1={8} x2={PL} y2={H - PB} stroke="#cbd5e1" strokeWidth={1} />`,
        `      <line x1={PL} y1={H - PB} x2={W - 8} y2={H - PB} stroke="#cbd5e1" strokeWidth={1} />`,
        `      <polyline points={points} fill="none" stroke="#2563eb" strokeWidth={2} />`,
        `      {data.filter((_, i) => i % Math.ceil(data.length / 7) === 0).map((d, i, arr) => {`,
        `        const idx = data.indexOf(d);`,
        `        const x   = PL + (idx / (data.length - 1)) * CW;`,
        `        return <text key={i} x={x} y={H - PB + 14} textAnchor="middle" fontSize={9} fill="#64748b">{d.label.slice(5)}</text>;`,
        `      })}`,
        `    </svg>`,
        `  );`,
        `}`,
      ].join("\n"),
    };
  },
};
