// ---------------------------------------------------------------------------
// Team Directory template — G-075 / NCD-002
//
// Produces a searchable employee directory with a data table and a detail
// panel that appears when a row is selected. Connects to any "employees"
// or "users" entity via the app-sdk useQuery hook.
// ---------------------------------------------------------------------------

import type { AppTemplate } from "./types.js";

export const teamDirectoryTemplate: AppTemplate = {
  meta: {
    id:          "team-directory",
    name:        "Team Directory",
    description: "Searchable directory with data table and detail panel. Connect to any people entity.",
    category:    "admin",
    thumbnail:   "/assets/templates/team-directory.png",
    requiredPermissions: ["entity:read"],
  },

  render(appName: string, slug: string): Record<string, string> {
    return {
      "/package.json": JSON.stringify(
        {
          name: slug,
          version: "0.1.0",
          dependencies: {
            react: "^18.2.0",
            "react-dom": "^18.2.0",
            "@oneplatform/app-sdk": "^1.0.0",
          },
        },
        null,
        2
      ),

      "/tsconfig.json": JSON.stringify(
        {
          compilerOptions: {
            target: "ES2022",
            module: "ESNext",
            moduleResolution: "bundler",
            jsx: "react-jsx",
            strict: true,
            esModuleInterop: true,
            allowSyntheticDefaultImports: true,
          },
          include: ["src"],
        },
        null,
        2
      ),

      "/src/index.tsx": [
        `import React from "react";`,
        `import { createRoot } from "react-dom/client";`,
        `import { AppProvider } from "@oneplatform/app-sdk";`,
        `import { App } from "./App.js";`,
        ``,
        `const container = document.getElementById("app");`,
        `if (!container) throw new Error("Root element #app not found");`,
        `createRoot(container).render(<AppProvider><App /></AppProvider>);`,
      ].join("\n"),

      "/src/App.tsx": [
        `/**`,
        ` * Replace "employees" with your actual people entity.`,
        ` * Expected fields: id, name, title, department, email, location, avatarUrl (optional).`,
        ` */`,
        `import React, { useState } from "react";`,
        `import { useQuery } from "@oneplatform/app-sdk";`,
        `import { DirectoryTable } from "./components/DirectoryTable.js";`,
        `import { DetailPanel } from "./components/DetailPanel.js";`,
        ``,
        `export interface Employee {`,
        `  id:          string;`,
        `  name:        string;`,
        `  title:       string;`,
        `  department:  string;`,
        `  email:       string;`,
        `  location:    string;`,
        `  avatarUrl?:  string;`,
        `}`,
        ``,
        `export function App() {`,
        `  const [search,   setSearch]   = useState("");`,
        `  const [selected, setSelected] = useState<Employee | null>(null);`,
        `  const { data, isLoading, error } = useQuery<Employee>("employees");`,
        ``,
        `  if (isLoading) return <div style={wrap}><p>Loading directory…</p></div>;`,
        `  if (error)     return <div style={wrap}><p style={{ color: "red" }}>Error: {error.message}</p></div>;`,
        ``,
        `  const q        = search.toLowerCase();`,
        `  const filtered = q === ""`,
        `    ? data`,
        `    : data.filter((e) =>`,
        `        e.name.toLowerCase().includes(q) ||`,
        `        e.department.toLowerCase().includes(q) ||`,
        `        e.title.toLowerCase().includes(q)`,
        `      );`,
        ``,
        `  return (`,
        `    <div style={wrap}>`,
        `      <h1 style={{ fontSize: "1.5rem", fontWeight: 700, marginBottom: "16px" }}>${appName}</h1>`,
        `      <input`,
        `        type="search"`,
        `        placeholder="Search by name, team, or title…"`,
        `        value={search}`,
        `        onChange={(e) => setSearch(e.target.value)}`,
        `        style={searchStyle}`,
        `        aria-label="Search employees"`,
        `      />`,
        `      <div style={{ display: "flex", gap: "24px", marginTop: "16px" }}>`,
        `        <div style={{ flex: 1, minWidth: 0 }}>`,
        `          <DirectoryTable employees={filtered} selected={selected} onSelect={setSelected} />`,
        `        </div>`,
        `        {selected !== null && (`,
        `          <div style={{ width: "280px", flexShrink: 0 }}>`,
        `            <DetailPanel employee={selected} onClose={() => setSelected(null)} />`,
        `          </div>`,
        `        )}`,
        `      </div>`,
        `    </div>`,
        `  );`,
        `}`,
        ``,
        `const wrap        = { padding: "24px", fontFamily: "system-ui, sans-serif" };`,
        `const searchStyle = { display: "block", width: "100%", maxWidth: "360px", padding: "8px 12px", border: "1px solid #cbd5e1", borderRadius: "8px", fontSize: "0.875rem", boxSizing: "border-box" as const };`,
      ].join("\n"),

      "/src/components/DirectoryTable.tsx": [
        `import React from "react";`,
        `import type { Employee } from "../App.js";`,
        ``,
        `interface Props {`,
        `  employees: Employee[];`,
        `  selected:  Employee | null;`,
        `  onSelect(e: Employee): void;`,
        `}`,
        ``,
        `export function DirectoryTable({ employees, selected, onSelect }: Props) {`,
        `  return (`,
        `    <table style={{ width: "100%", borderCollapse: "collapse", fontSize: "0.875rem" }}>`,
        `      <thead>`,
        `        <tr style={{ background: "#f1f5f9" }}>`,
        `          <th style={th}>Name</th>`,
        `          <th style={th}>Title</th>`,
        `          <th style={th}>Department</th>`,
        `          <th style={th}>Location</th>`,
        `        </tr>`,
        `      </thead>`,
        `      <tbody>`,
        `        {employees.map((e) => (`,
        `          <tr`,
        `            key={e.id}`,
        `            onClick={() => onSelect(e)}`,
        `            style={{`,
        `              borderBottom: "1px solid #e2e8f0",`,
        `              background: selected?.id === e.id ? "#eff6ff" : undefined,`,
        `              cursor: "pointer",`,
        `            }}`,
        `          >`,
        `            <td style={td}><strong>{e.name}</strong></td>`,
        `            <td style={td}>{e.title}</td>`,
        `            <td style={td}>{e.department}</td>`,
        `            <td style={td}>{e.location}</td>`,
        `          </tr>`,
        `        ))}`,
        `        {employees.length === 0 && (`,
        `          <tr><td colSpan={4} style={{ ...td, textAlign: "center", color: "#94a3b8" }}>No results.</td></tr>`,
        `        )}`,
        `      </tbody>`,
        `    </table>`,
        `  );`,
        `}`,
        ``,
        `const th: React.CSSProperties = { padding: "10px 12px", textAlign: "left", fontWeight: 600 };`,
        `const td: React.CSSProperties = { padding: "10px 12px" };`,
      ].join("\n"),

      "/src/components/DetailPanel.tsx": [
        `import React from "react";`,
        `import type { Employee } from "../App.js";`,
        ``,
        `interface Props { employee: Employee; onClose(): void; }`,
        ``,
        `export function DetailPanel({ employee, onClose }: Props) {`,
        `  return (`,
        `    <div style={{ border: "1px solid #e2e8f0", borderRadius: "8px", padding: "20px", background: "#fff" }}>`,
        `      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", marginBottom: "16px" }}>`,
        `        <div style={{ width: "48px", height: "48px", borderRadius: "50%", background: "#2563eb", display: "flex", alignItems: "center", justifyContent: "center", color: "#fff", fontWeight: 700, fontSize: "1.125rem" }}>`,
        `          {employee.name.charAt(0).toUpperCase()}`,
        `        </div>`,
        `        <button onClick={onClose} style={{ background: "none", border: "none", cursor: "pointer", color: "#64748b", fontSize: "1rem" }} aria-label="Close detail panel">✕</button>`,
        `      </div>`,
        `      <h3 style={{ fontSize: "1rem", fontWeight: 700, marginBottom: "4px" }}>{employee.name}</h3>`,
        `      <p style={{ color: "#64748b", fontSize: "0.875rem", marginBottom: "16px" }}>{employee.title}</p>`,
        `      <dl style={{ display: "grid", gap: "8px", fontSize: "0.8125rem" }}>`,
        `        <Field label="Department" value={employee.department} />`,
        `        <Field label="Email"      value={employee.email} />`,
        `        <Field label="Location"   value={employee.location} />`,
        `      </dl>`,
        `    </div>`,
        `  );`,
        `}`,
        ``,
        `function Field({ label, value }: { label: string; value: string }) {`,
        `  return (`,
        `    <div>`,
        `      <dt style={{ color: "#94a3b8", fontSize: "0.75rem", textTransform: "uppercase", letterSpacing: "0.05em" }}>{label}</dt>`,
        `      <dd style={{ margin: 0, fontWeight: 500 }}>{value}</dd>`,
        `    </div>`,
        `  );`,
        `}`,
      ].join("\n"),
    };
  },
};
