#!/bin/bash
# docker/postgres/set-passwords.sh
#
# Executed by postgres:16-alpine on first container start via
# /docker-entrypoint-initdb.d/ (after init.sql).
# Reads per-service passwords generated by op-init and applies them via
# ALTER ROLE so the CHANGE_ME placeholder in init.sql never persists.
#
# This script runs inside the postgres initdb environment where $POSTGRES_USER
# and $POSTGRES_DB are set by the postgres image entrypoint.
#
# Ref spec §3 "PostgreSQL: Per-Service Schemas", §2 "Startup Sequence".

set -euo pipefail

INIT_DIR="/data/init"

# read_password reads a password file and trims trailing whitespace/newlines.
# Fails loudly if the file is absent — a missing file means op-init did not
# complete successfully, which is a hard startup error.
read_password() {
  local file="$1"
  if [ ! -f "$file" ]; then
    echo "ERROR: Password file not found: $file" >&2
    echo "       Did op-init complete successfully? Check the op-init container logs." >&2
    exit 1
  fi
  tr -d '[:space:]' < "$file"
}

echo "[postgres-init] Applying generated service role passwords..."

# ── Per-service role passwords ───────────────────────────────────────────────
# Each role was created in init.sql with a CHANGE_ME placeholder. We now
# replace those with the real passwords generated by op-init.

for SERVICE in auth gateway ingestion ontology pipeline execution app logging plugin; do
  PW=$(read_password "$INIT_DIR/db_password_${SERVICE}.txt")
  # Use psql variable binding to prevent SQL injection from password contents.
  # The :'-quoted_var' syntax causes psql to properly quote/escape the value.
  # NOTE: psql only interpolates :'var' for SQL read from stdin/-f, NOT from -c
  # command strings, so the statement must be piped in rather than passed via -c.
  echo "ALTER ROLE ${SERVICE}_service_role WITH PASSWORD :'safe_pw';" | \
    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" \
      -v "safe_pw=$PW"
  echo "[postgres-init] Password set for ${SERVICE}_service_role"
done

# ── PgBouncer admin/stats passwords ─────────────────────────────────────────
# pgbouncer_admin and pgbouncer_stats are PostgreSQL roles used by PgBouncer
# for admin console access. They must also have their CHANGE_ME passwords replaced.

for PGBUSER in pgbouncer_admin pgbouncer_stats; do
  # Only set the password if the role exists (it may not in minimal deployments).
  ROLE_EXISTS=$(psql -t -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" \
    -c "SELECT 1 FROM pg_roles WHERE rolname = '${PGBUSER}';" | tr -d '[:space:]')
  if [ "$ROLE_EXISTS" = "1" ]; then
    PW=$(read_password "$INIT_DIR/db_password_${PGBUSER}.txt")
    # Use psql variable binding to prevent SQL injection from password contents.
    # Piped via stdin so :'safe_pw' interpolation runs (it does not for -c).
    echo "ALTER ROLE ${PGBUSER} WITH PASSWORD :'safe_pw';" | \
      psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" \
        -v "safe_pw=$PW"
    echo "[postgres-init] Password set for ${PGBUSER}"
  else
    echo "[postgres-init] Role ${PGBUSER} does not exist, skipping password set"
  fi
done

# ── Postgres superuser password ─────────────────────────────────────────────
# The POSTGRES_PASSWORD env var used during container initialisation may have
# been left at the dev default ("dev_postgres_superuser"). Overwrite it with the
# op-init generated password so the superuser is always protected by a strong
# credential after first boot, regardless of what POSTGRES_PASSWORD was set to.
SUPER_PW=$(read_password "$INIT_DIR/db_password_postgres_superuser.txt")
# Piped via stdin so :'safe_pw' interpolation runs (it does not for -c).
echo "ALTER ROLE ${POSTGRES_USER} WITH PASSWORD :'safe_pw';" | \
  psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" \
    -v "safe_pw=$SUPER_PW"
echo "[postgres-init] Postgres superuser password reset to op-init generated value."

echo "[postgres-init] All service role passwords applied successfully."
