import type pg from "pg";
import { z } from "zod";
import { encodeCursor, decodeCursor } from "@oneplatform/core";
import type {
  LogEventRow,
  CreateLogEventData,
  LogQueryParams,
} from "./types.js";

export interface ExportQueryOptions {
  tenantId?: string;
  service?: string;
  level?: "debug" | "info" | "warn" | "error";
  traceId?: string;
  search?: string;
  from: string;
  to: string;
  chunkSize: number;
  // Keyset anchor for stable pagination — avoids OFFSET skipping rows inserted
  // mid-export and keeps performance flat regardless of how deep into the result
  // set the caller is (OFFSET requires scanning all prior rows).
  afterCreatedAt?: string;
  afterId?: string;
}

// OP_CURSOR_SECRET is validated at startup; the assertion here is a belt-and-
// suspenders guard for the rare case where this module is loaded in isolation.
function getCursorSecret(): string {
  const secret = process.env["OP_CURSOR_SECRET"];
  if (!secret) throw new Error("OP_CURSOR_SECRET is required");
  return secret;
}

// Validated shape of a decoded pagination cursor. Casting the raw decoded
// object directly to string fields is unsafe — a tampered or malformed cursor
// must fail loudly rather than produce a SQL type error at query time.
const CursorPayloadSchema = z.object({
  createdAt: z.string().datetime(),
  id: z.string().uuid(),
});

export class LogEventRepository {
  constructor(private readonly db: pg.Pool) {}

  /**
   * Bulk insert via unnest — single round-trip for the entire batch.
   *
   * ON CONFLICT DO NOTHING is intentionally absent: the events table has a
   * UUID primary key generated by the DB (gen_random_uuid()) and no composite
   * unique index on the payload columns, so there is no conflict condition to
   * match against. Adding the clause with no target conflict index would be a
   * no-op at best and misleading at worst.
   */
  async insertBatch(events: CreateLogEventData[]): Promise<void> {
    if (events.length === 0) return;

    const tenantIds = events.map((e) => e.tenantId);
    const traceIds = events.map((e) => e.traceId);
    const services = events.map((e) => e.service);
    const levels = events.map((e) => e.level);
    const messages = events.map((e) => e.message);
    const metadatas = events.map((e) => JSON.stringify(e.metadata));
    const createdAts = events.map((e) => e.createdAt.toISOString());

    await this.db.query(
      `INSERT INTO logging.events
         (tenant_id, trace_id, service, level, message, metadata, created_at)
       SELECT
         unnest($1::text[])        AS tenant_id,
         unnest($2::text[])        AS trace_id,
         unnest($3::text[])        AS service,
         unnest($4::text[])        AS level,
         unnest($5::text[])        AS message,
         unnest($6::jsonb[])       AS metadata,
         unnest($7::timestamptz[]) AS created_at`,
      [tenantIds, traceIds, services, levels, messages, metadatas, createdAts]
    );
  }

  /**
   * Parameterized query builder — user values are always bound as positional
   * parameters, never interpolated into the SQL string.
   */
  async query(
    params: LogQueryParams
  ): Promise<{ data: LogEventRow[]; nextCursor: string | null }> {
    const conditions: string[] = [];
    const args: unknown[] = [];
    let n = 1;

    if (params.tenantId !== undefined) {
      conditions.push(`tenant_id = $${n++}`);
      args.push(params.tenantId);
    }
    if (params.service !== undefined) {
      conditions.push(`service = $${n++}`);
      args.push(params.service);
    }
    if (params.level !== undefined) {
      conditions.push(`level = $${n++}`);
      args.push(params.level);
    }
    if (params.traceId !== undefined) {
      conditions.push(`trace_id = $${n++}`);
      args.push(params.traceId);
    }
    if (params.search !== undefined) {
      // plainto_tsquery handles arbitrary user input safely — it normalises
      // tokens and never raises a syntax error on special characters.
      // phraseto_tsquery is used when the user wraps a phrase in quotes.
      if (params.search.startsWith('"') && params.search.endsWith('"')) {
        conditions.push(`search_vec @@ phraseto_tsquery('english', $${n++})`);
        args.push(params.search.slice(1, -1));
      } else {
        conditions.push(`search_vec @@ plainto_tsquery('english', $${n++})`);
        args.push(params.search);
      }
    }
    if (params.from !== undefined) {
      conditions.push(`created_at >= $${n++}`);
      args.push(params.from);
    }
    if (params.to !== undefined) {
      conditions.push(`created_at < $${n++}`);
      args.push(params.to);
    }

    let cursorClause = "";
    if (params.cursor !== undefined) {
      const raw = await decodeCursor(params.cursor, getCursorSecret());
      const cursor = CursorPayloadSchema.parse(raw);
      const keyword = conditions.length > 0 ? "AND" : "WHERE";
      cursorClause = `${keyword} (created_at, id) < ($${n++}::timestamptz, $${n++}::uuid)`;
      args.push(cursor.createdAt, cursor.id);
    }

    // Fetch one extra row to determine whether another page exists, then strip it.
    const fetchLimit = params.limit + 1;
    args.push(fetchLimit);
    const limitParam = `$${n}`;

    const whereClause =
      conditions.length > 0 ? `WHERE ${conditions.join(" AND ")}` : "";

    const sql = `
      SELECT id, tenant_id, trace_id, service, level, message, metadata, created_at
      FROM logging.events
      ${whereClause} ${cursorClause}
      ORDER BY created_at DESC, id DESC
      LIMIT ${limitParam}
    `;

    const result = await this.db.query<LogEventRow>(sql, args);
    const rows = result.rows;
    const hasMore = rows.length > params.limit;
    const data = hasMore ? rows.slice(0, params.limit) : rows;

    let nextCursor: string | null = null;
    if (hasMore && data.length > 0) {
      const lastRow = data[data.length - 1];
      // lastRow is always defined here — data.length > 0 is asserted above
      nextCursor = await encodeCursor(
        {
          createdAt: (lastRow as LogEventRow).created_at.toISOString(),
          id: (lastRow as LogEventRow).id,
        },
        getCursorSecret()
      );
    }

    return { data, nextCursor };
  }

  /**
   * Fetch a single log event by its UUID primary key.
   * Returns null when no matching row exists (across all partitions).
   *
   * When tenantId is provided the query includes a WHERE tenant_id clause
   * so callers cannot read log events belonging to other tenants.
   */
  async findById(id: string, tenantId?: string): Promise<LogEventRow | null> {
    if (tenantId !== undefined) {
      const result = await this.db.query<LogEventRow>(
        `SELECT id, tenant_id, trace_id, service, level, message, metadata, created_at
         FROM logging.events
         WHERE id = $1 AND tenant_id = $2
         LIMIT 1`,
        [id, tenantId]
      );
      return result.rows[0] ?? null;
    }
    const result = await this.db.query<LogEventRow>(
      `SELECT id, tenant_id, trace_id, service, level, message, metadata, created_at
       FROM logging.events
       WHERE id = $1
       LIMIT 1`,
      [id]
    );
    return result.rows[0] ?? null;
  }

  /**
   * Fetch a page of rows for streaming export using keyset pagination.
   *
   * Ascending order is intentional for export (matches natural write order for
   * log analysis tools). Callers pass the last row's (created_at, id) as the
   * anchor for the next page. OFFSET is not used because it scans all prior
   * rows and skips any rows inserted mid-export.
   */
  async exportPage(opts: ExportQueryOptions): Promise<LogEventRow[]> {
    const conditions: string[] = [];
    const args: unknown[] = [];
    let n = 1;

    if (opts.tenantId !== undefined) {
      conditions.push(`tenant_id = $${n++}`);
      args.push(opts.tenantId);
    }
    if (opts.service !== undefined) {
      conditions.push(`service = $${n++}`);
      args.push(opts.service);
    }
    if (opts.level !== undefined) {
      conditions.push(`level = $${n++}`);
      args.push(opts.level);
    }
    if (opts.traceId !== undefined) {
      conditions.push(`trace_id = $${n++}`);
      args.push(opts.traceId);
    }
    if (opts.search !== undefined) {
      if (opts.search.startsWith('"') && opts.search.endsWith('"')) {
        conditions.push(`search_vec @@ phraseto_tsquery('english', $${n++})`);
        args.push(opts.search.slice(1, -1));
      } else {
        conditions.push(`search_vec @@ plainto_tsquery('english', $${n++})`);
        args.push(opts.search);
      }
    }
    conditions.push(`created_at >= $${n++}`);
    args.push(opts.from);
    conditions.push(`created_at < $${n++}`);
    args.push(opts.to);

    // Keyset anchor: skip rows at-or-before the last row of the previous page
    let keysetClause = "";
    if (opts.afterCreatedAt !== undefined && opts.afterId !== undefined) {
      keysetClause = `AND (created_at, id) > ($${n++}::timestamptz, $${n++}::uuid)`;
      args.push(opts.afterCreatedAt, opts.afterId);
    }

    args.push(opts.chunkSize);
    const limitParam = n;

    const whereClause = `WHERE ${conditions.join(" AND ")}`;

    const sql = `
      SELECT id, tenant_id, trace_id, service, level, message, metadata, created_at
      FROM logging.events
      ${whereClause} ${keysetClause}
      ORDER BY created_at ASC, id ASC
      LIMIT $${limitParam}
    `;

    const result = await this.db.query<LogEventRow>(sql, args);
    return result.rows;
  }

  /**
   * Fetch all events for a trace chain across all services.
   * The (trace_id, created_at DESC) partial index makes this efficient;
   * the WHERE trace_id <> '' exclusion means empty-string system events
   * are not indexed and cannot match here.
   */
  async queryByTraceId(traceId: string, tenantId?: string): Promise<LogEventRow[]> {
    if (tenantId !== undefined) {
      const result = await this.db.query<LogEventRow>(
        `SELECT id, tenant_id, trace_id, service, level, message, metadata, created_at
         FROM logging.events
         WHERE trace_id = $1 AND tenant_id = $2
         ORDER BY created_at DESC, id DESC
         LIMIT 500`,
        [traceId, tenantId]
      );
      return result.rows;
    }
    const result = await this.db.query<LogEventRow>(
      `SELECT id, tenant_id, trace_id, service, level, message, metadata, created_at
       FROM logging.events
       WHERE trace_id = $1
       ORDER BY created_at DESC, id DESC
       LIMIT 500`,
      [traceId]
    );
    return result.rows;
  }
}
