/**
 * Level 1 integration tests: Auth service bootstrap flow.
 *
 * Bootstrap is a one-shot operation: it creates the first tenant + platform-admin
 * user and permanently locks the endpoint afterward. These tests use a fresh
 * createServiceApp() instance per describe block so each test suite starts with
 * a clean in-memory bootstrap token and a reset bootstrap_state row.
 *
 * WHY a per-suite app instance: the in-memory token inside createServiceApp() is
 * cleared after a successful bootstrap call. If we shared one app across suites
 * the second bootstrap attempt would fail with TOKEN_MISSING rather than the
 * expected 410 ALREADY_COMPLETED.
 */

import { describe, it, expect, beforeAll, afterAll } from "vitest";
import pg from "pg";
import { buildTestApp } from "../helpers/test-app.js";
import { cleanupAuthTenant, resetBootstrapState } from "../helpers/tenant.js";
// createServiceApp accepts a plain-string token for test injection (design §3.5)
import { createServiceApp } from "../../dist/index.js";

// A valid 64-hex-char bootstrap token injected at factory construction time.
// Real tokens are generated by op-init; in tests we supply a known value so we
// can use it in POST /api/v1/bootstrap without reading from the filesystem.
const VALID_TOKEN = "a".repeat(64);

// ---------------------------------------------------------------------------
// Shared cleanup pool (superuser — bypasses RLS)
// ---------------------------------------------------------------------------

let db: pg.Pool;

// ---------------------------------------------------------------------------
// Helper: build a fresh app instance with the test bootstrap token pre-loaded
// ---------------------------------------------------------------------------

async function buildBootstrapApp() {
  const { app, cleanup } = await createServiceApp({
    databaseUrl: process.env["OP_DATABASE_URL"]!,
    redisUrl: process.env["OP_REDIS_URL"]!,
    jwtSecret: process.env["OP_JWT_SECRET"]!,
    masterKey: Buffer.from(process.env["OP_MASTER_KEY"]!, "base64"),
    allowedOrigins: ["http://localhost:3000"],
    bootstrapToken: VALID_TOKEN,
  });
  return { app, cleanup };
}

// ---------------------------------------------------------------------------
// Helper: POST /api/v1/bootstrap with the valid token
// ---------------------------------------------------------------------------

async function postBootstrap(
  app: Awaited<ReturnType<typeof buildBootstrapApp>>["app"],
  overrides: Record<string, unknown> = {},
  // Use a unique per-test IP to avoid tripping the in-memory rate limiter
  // (3 attempts per IP per 10 min). Since the module-level Map persists across
  // all tests in this file, each test must supply a distinct IP.
  callerIp = "10.0.0.1",
) {
  return app.fetch(
    new Request("http://localhost/api/v1/bootstrap", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        // X-Forwarded-For overrides the IP used for rate limiting
        "X-Forwarded-For": callerIp,
      },
      body: JSON.stringify({
        adminEmail: "admin@example.com",
        adminPassword: "Correct-Horse-Battery-Staple-99",
        tenantName: "Test Tenant",
        bootstrapToken: VALID_TOKEN,
        ...overrides,
      }),
    }),
  );
}

// ---------------------------------------------------------------------------

describe("Auth service — bootstrap flow", () => {
  beforeAll(async () => {
    // We only need the DB pool for cleanup queries; buildTestApp() also runs
    // migrations (idempotent) which primes the schema for the test suite.
    // The app instance is thrown away immediately after migrations complete.
    const result = await buildTestApp();
    db = result.db;
    await result.cleanup();
    // Ensure bootstrap_state starts clean for the entire suite
    await resetBootstrapState(db);
  });

  afterAll(async () => {
    await db.end();
  });

  // -------------------------------------------------------------------------

  it("GET /api/v1/bootstrap/status returns completed=false before bootstrap", async () => {
    // Use a throwaway app — we just need a fresh service to query status.
    // The bootstrap_state row was reset in the previous afterAll; this
    // ensures the default migrated state is "not completed".
    const { app, cleanup } = await buildBootstrapApp();
    try {
      // First ensure bootstrap state is clean
      await resetBootstrapState(db);

      const res = await app.fetch(
        new Request("http://localhost/api/v1/bootstrap/status"),
      );

      expect(res.status).toBe(200);
      const body = await res.json() as { completed: boolean };
      expect(body.completed).toBe(false);
    } finally {
      await cleanup();
    }
  });

  // -------------------------------------------------------------------------

  it("POST /api/v1/bootstrap with valid token creates admin user and returns tokens", async () => {
    const { app, cleanup } = await buildBootstrapApp();
    // Track the tenantId so we can clean up after this test
    let createdTenantId: string | undefined;

    try {
      await resetBootstrapState(db);

      // Unique IP per test prevents module-level rate limiter from accumulating
      const res = await postBootstrap(app, {}, "10.0.0.2");

      expect(res.status).toBe(201);
      const body = await res.json() as {
        tenantId: string;
        adminUserId: string;
        accessToken: string;
        refreshToken: string;
        expiresIn: number;
      };

      expect(body.tenantId).toMatch(
        /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/,
      );
      expect(body.adminUserId).toMatch(
        /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/,
      );
      expect(body.accessToken).toBeTruthy();
      expect(body.refreshToken).toBeTruthy();
      expect(typeof body.expiresIn).toBe("number");
      expect(body.expiresIn).toBeGreaterThan(0);

      createdTenantId = body.tenantId;
    } finally {
      await cleanup();
      // Reset bootstrap state before deleting tenant rows — the bootstrap_state
      // row holds FK references to admin_user_id and first_tenant_id.
      await resetBootstrapState(db);
      if (createdTenantId !== undefined) {
        await cleanupAuthTenant(db, createdTenantId);
      }
    }
  });

  // -------------------------------------------------------------------------

  it("POST /api/v1/bootstrap a second time returns 410 (already completed)", async () => {
    // We need TWO separate app instances: the first performs the successful
    // bootstrap (clearing the in-memory token), the second attempt uses
    // a fresh instance with the token still loaded so the comparison path runs.
    let createdTenantId: string | undefined;
    const { app: app1, cleanup: cleanup1 } = await buildBootstrapApp();
    const { app: app2, cleanup: cleanup2 } = await buildBootstrapApp();

    try {
      await resetBootstrapState(db);

      // Successful first bootstrap — unique IPs so the rate limiter window
      // doesn't carry over from the previous test in this file.
      const first = await postBootstrap(app1, {}, "10.0.0.3");
      expect(first.status).toBe(201);
      const firstBody = await first.json() as { tenantId: string };
      createdTenantId = firstBody.tenantId;

      // Second attempt on a fresh app — bootstrap_state.completed = true, so 410
      const second = await postBootstrap(app2, {}, "10.0.0.4");
      expect(second.status).toBe(410);
    } finally {
      await cleanup1();
      await cleanup2();
      await resetBootstrapState(db);
      if (createdTenantId !== undefined) {
        await cleanupAuthTenant(db, createdTenantId);
      }
    }
  });

  // -------------------------------------------------------------------------

  it("GET /api/v1/bootstrap/status returns completed=true after bootstrap", async () => {
    let createdTenantId: string | undefined;
    const { app: appWriter, cleanup: cleanupWriter } = await buildBootstrapApp();
    const { app: appReader, cleanup: cleanupReader } = await buildBootstrapApp();

    try {
      await resetBootstrapState(db);

      const bootstrapRes = await postBootstrap(appWriter, {}, "10.0.0.5");
      expect(bootstrapRes.status).toBe(201);
      const bootstrapBody = await bootstrapRes.json() as { tenantId: string };
      createdTenantId = bootstrapBody.tenantId;

      const statusRes = await appReader.fetch(
        new Request("http://localhost/api/v1/bootstrap/status"),
      );

      expect(statusRes.status).toBe(200);
      const statusBody = await statusRes.json() as { completed: boolean };
      expect(statusBody.completed).toBe(true);
    } finally {
      await cleanupWriter();
      await cleanupReader();
      await resetBootstrapState(db);
      if (createdTenantId !== undefined) {
        await cleanupAuthTenant(db, createdTenantId);
      }
    }
  });

  // -------------------------------------------------------------------------

  it("POST /api/v1/bootstrap with wrong token returns 401", async () => {
    const { app, cleanup } = await buildBootstrapApp();

    try {
      await resetBootstrapState(db);

      const res = await postBootstrap(
        app,
        { bootstrapToken: "b".repeat(64) }, // wrong token
        "10.0.0.6",
      );

      // The service returns 401 for a token mismatch
      expect(res.status).toBe(401);
    } finally {
      await cleanup();
      // bootstrap_state was not modified (token rejected before DB write)
    }
  });
});
