/**
 * Entity type declaration generator.
 *
 * Converts ontology entity schemas (from GET /api/v1/ontology) into a
 * TypeScript module augmentation file that gives app developers type-safe
 * useQuery<EntityTypeMap["customer"]>("customer") calls.
 *
 * This logic is intentionally duplicated from packages/app-sdk/src/dev/generate-types.ts
 * so that the CLI does not need to depend on the app-sdk package at runtime.
 * Keep the two files in sync when changing TYPE_MAP or the generated output format.
 */

// ─── Field type mapping ───────────────────────────────────────────────────────

/**
 * Maps platform fieldType strings to TypeScript primitive types.
 * "enum" is handled per-field using enumValues to produce a union literal type.
 */
const TYPE_MAP: Record<string, string> = {
  text: "string",
  integer: "number",
  float: "number",
  boolean: "boolean",
  datetime: "string", // ISO 8601 string
  json: "Record<string, unknown>",
  uuid: "string",
  array: "unknown[]",
  enum: "string", // overridden per-field when enumValues is present
};

// ─── Shared types ─────────────────────────────────────────────────────────────

export interface EntityField {
  slug: string;
  fieldType: string;
  required: boolean;
  enumValues?: string[];
}

export interface OntologyEntitySchema {
  slug: string;
  fields: EntityField[];
}

// ─── Conversion helpers ───────────────────────────────────────────────────────

/**
 * Converts a single entity field definition to its TypeScript property line.
 *
 * Enum fields with enumValues produce a union literal:
 *   status?: "active" | "inactive" | "pending";
 */
export function fieldToTs(field: EntityField): string {
  let tsType: string;

  if (field.fieldType === "enum" && field.enumValues && field.enumValues.length > 0) {
    tsType = field.enumValues.map((v) => JSON.stringify(v)).join(" | ");
  } else {
    tsType = TYPE_MAP[field.fieldType] ?? "unknown";
  }

  const optional = field.required ? "" : "?";
  return `    ${field.slug}${optional}: ${tsType};`;
}

// ─── Main generator ───────────────────────────────────────────────────────────

/**
 * Generates the full content of an `op-types.d.ts` declaration file.
 *
 * The output augments the @oneplatform/app-sdk module by extending the
 * EntityTypeMap interface, enabling type-safe useQuery<T>() calls.
 *
 * @param entities  Entity schemas from GET /api/v1/ontology
 * @returns         TypeScript declaration file content, ready to write to disk
 */
export function generateEntityTypes(entities: OntologyEntitySchema[]): string {
  if (entities.length === 0) {
    return [
      "// Auto-generated by `op sdk generate-types`. Do not edit.",
      "// No ontology entities found — run after defining entity schemas.",
      "declare module \"@oneplatform/app-sdk\" {",
      "  // eslint-disable-next-line @typescript-eslint/no-empty-interface",
      "  interface EntityTypeMap {}",
      "}",
      "",
    ].join("\n");
  }

  const entityInterfaces = entities.map((entity) => {
    const fieldLines = entity.fields.map(fieldToTs);
    // Inject an id field if the entity schema does not already declare one.
    // The platform adds id to all persisted entities.
    const hasId = entity.fields.some((f) => f.slug === "id");
    const allLines = hasId ? fieldLines : ["    id: string;", ...fieldLines];

    return [
      `    ${entity.slug}: {`,
      ...allLines,
      "    };",
    ].join("\n");
  });

  return [
    "// Auto-generated by `op sdk generate-types`. Do not edit.",
    "// Re-run `op sdk generate-types` after changing entity schemas.",
    "declare module \"@oneplatform/app-sdk\" {",
    "  interface EntityTypeMap {",
    entityInterfaces.join("\n"),
    "  }",
    "}",
    "",
  ].join("\n");
}
