import { createCipheriv, createDecipheriv, hkdfSync, randomBytes } from "crypto";

// Wire format: base64( salt[32] | iv[12] | authTag[16] | ciphertext[...] )
// salt  — unique per encryption, passed to HKDF for per-credential key derivation
// iv    — unique per encryption, required for AES-GCM nonce uniqueness
// authTag — AES-GCM authentication tag, detects any tampering
const SALT_BYTES = 32;
const IV_BYTES = 12; // 96-bit nonce — GCM standard recommendation
const TAG_BYTES = 16; // 128-bit authentication tag

// Derive a 256-bit AES key from the master key and a per-credential salt.
// HKDF-SHA256 ensures that each credential uses a distinct key even though
// they share one master key — compromising one credential does not help an
// attacker decrypt others (spec §13, ADR-11).
function deriveKey(masterKey: Buffer, salt: Buffer): Buffer {
  return Buffer.from(
    hkdfSync("sha256", masterKey, salt, "oneplatform-credential-v1", 32)
  );
}

export async function encrypt(plaintext: string, masterKey: Buffer): Promise<string> {
  const salt = randomBytes(SALT_BYTES);
  const iv = randomBytes(IV_BYTES);
  const key = deriveKey(masterKey, salt);

  const cipher = createCipheriv("aes-256-gcm", key, iv);
  const ciphertext = Buffer.concat([
    cipher.update(plaintext, "utf8"),
    cipher.final(),
  ]);
  const authTag = cipher.getAuthTag();

  const blob = Buffer.concat([salt, iv, authTag, ciphertext]);
  return blob.toString("base64");
}

export async function decrypt(blob: string, masterKey: Buffer): Promise<string> {
  const raw = Buffer.from(blob, "base64");

  if (raw.length < SALT_BYTES + IV_BYTES + TAG_BYTES) {
    throw new Error("Encrypted blob is too short to be valid");
  }

  const salt = raw.subarray(0, SALT_BYTES);
  const iv = raw.subarray(SALT_BYTES, SALT_BYTES + IV_BYTES);
  const authTag = raw.subarray(SALT_BYTES + IV_BYTES, SALT_BYTES + IV_BYTES + TAG_BYTES);
  const ciphertext = raw.subarray(SALT_BYTES + IV_BYTES + TAG_BYTES);

  const key = deriveKey(masterKey, salt);
  const decipher = createDecipheriv("aes-256-gcm", key, iv);
  decipher.setAuthTag(authTag);

  // Throws if the auth tag does not match — detects both tampering and wrong key
  const plaintext = Buffer.concat([decipher.update(ciphertext), decipher.final()]);
  return plaintext.toString("utf8");
}

// loadMasterKey reads OP_MASTER_KEY from the environment and returns it as a
// raw Buffer. Called once at service startup; throws loudly if absent.
export function loadMasterKey(): Buffer {
  const raw = process.env["OP_MASTER_KEY"];
  if (!raw) {
    throw new Error(
      "OP_MASTER_KEY is not set. Cannot initialize credential vault."
    );
  }
  // Key is base64-encoded 32 bytes generated by op-init (spec §2)
  const key = Buffer.from(raw, "base64");
  if (key.length !== 32) {
    throw new Error(
      `OP_MASTER_KEY must be a 32-byte base64-encoded value (got ${key.length} bytes)`
    );
  }
  return key;
}
