#!/bin/sh
# docker/pgbouncer/pgbouncer-entrypoint.sh
#
# Renders userlist.txt from the template using passwords generated by op-init,
# then execs the standard pgbouncer entrypoint.
#
# The template lives at /etc/pgbouncer/userlist.txt.template (read-only mount).
# The rendered userlist is written to /tmp/userlist.txt so it resides on a
# writable path rather than a read-only config volume.
# pgbouncer.ini auth_file is overridden to point at the rendered path.
#
# Ref spec §3 "PgBouncer Configuration", §2 "Startup Sequence".

set -e

INIT_DIR="/data/init"
TEMPLATE="/etc/pgbouncer/userlist.txt.template"
RENDERED="/tmp/userlist.txt"
PGBOUNCER_CONF="/etc/pgbouncer/pgbouncer.ini"
RENDERED_CONF="/tmp/pgbouncer.ini"

if [ ! -f "$INIT_DIR/ready" ]; then
  echo "[pgbouncer-entrypoint] FATAL: op-init has not completed ($INIT_DIR/ready missing)." >&2
  exit 1
fi

echo "[pgbouncer-entrypoint] Rendering userlist.txt from template..."

cp "$TEMPLATE" "$RENDERED"

for SERVICE in gateway auth ingestion ontology pipeline execution app logging plugin; do
  PW_FILE="$INIT_DIR/db_password_${SERVICE}.txt"
  if [ ! -f "$PW_FILE" ]; then
    echo "[pgbouncer-entrypoint] FATAL: DB password file missing: $PW_FILE" >&2
    exit 1
  fi
  PW=$(tr -d '[:space:]' < "$PW_FILE")
  sed -i "s|PGBOUNCER_PASSWORD_${SERVICE}\b|${PW}|g" "$RENDERED"
done

for PGBUSER in pgbouncer_admin pgbouncer_stats; do
  PW_FILE="$INIT_DIR/db_password_${PGBUSER}.txt"
  if [ ! -f "$PW_FILE" ]; then
    echo "[pgbouncer-entrypoint] FATAL: PgBouncer admin password file missing: $PW_FILE" >&2
    exit 1
  fi
  PW=$(tr -d '[:space:]' < "$PW_FILE")
  sed -i "s|PGBOUNCER_PASSWORD_${PGBUSER}|${PW}|g" "$RENDERED"
done

if grep -q 'PGBOUNCER_PASSWORD_' "$RENDERED"; then
  echo "[pgbouncer-entrypoint] FATAL: Unreplaced PGBOUNCER_PASSWORD_ placeholder in rendered userlist." >&2
  exit 1
fi

# Rewrite auth_file in pgbouncer.ini to point at the rendered path on tmpfs.
# This avoids mounting the ini file read-write and keeps the config volume clean.
cp "$PGBOUNCER_CONF" "$RENDERED_CONF"
sed -i "s|auth_file = /etc/pgbouncer/userlist.txt|auth_file = $RENDERED|g" "$RENDERED_CONF"

echo "[pgbouncer-entrypoint] userlist.txt rendered. Starting pgbouncer..."

exec pgbouncer "$RENDERED_CONF"
