#!/usr/bin/env bash
#
# dev-test-start.sh — start the isolated OnePlatform dev-test stack.
#
# Builds all images from source, launches the full 9-service stack plus
# infrastructure on the op-dev-test network/project, waits for every container
# to report healthy, then prints the access URLs and default credentials.
#
# This stack is completely isolated from the main docker-compose.yml: separate
# network (op-dev-test), separate volumes (op-dev-test-*), separate ports (5xxx).

set -euo pipefail

# Resolve repo root from this script's location so it works from any CWD.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

COMPOSE_FILE="${SCRIPT_DIR}/docker-compose.dev-test.yml"
PROJECT="op-dev-test"

cd "${REPO_ROOT}"

echo "==> Building and starting OnePlatform dev-test stack (project: ${PROJECT})"
echo "    Compose file: ${COMPOSE_FILE}"
echo

docker compose -f "${COMPOSE_FILE}" -p "${PROJECT}" up --build -d

# ── Wait for healthchecks ────────────────────────────────────────────────────
# Poll until no container is in "starting"/"unhealthy", up to a timeout.
echo
echo "==> Waiting for services to become healthy (timeout 300s)..."

DEADLINE=$(( $(date +%s) + 300 ))
while true; do
  # List containers in this project with their health status (if any).
  STATUS="$(docker compose -f "${COMPOSE_FILE}" -p "${PROJECT}" ps --format '{{.Name}} {{.Health}}' 2>/dev/null || true)"

  # Count containers that have a healthcheck but are not yet healthy.
  UNHEALTHY="$(echo "${STATUS}" | awk '$2 != "" && $2 != "healthy" {print $1}')"

  if [ -z "${UNHEALTHY}" ]; then
    echo "==> All health-checked services are healthy."
    break
  fi

  if [ "$(date +%s)" -ge "${DEADLINE}" ]; then
    echo "!! Timed out waiting for the following services to become healthy:" >&2
    echo "${UNHEALTHY}" | sed 's/^/     - /' >&2
    echo "   Inspect with: docker compose -f ${COMPOSE_FILE} -p ${PROJECT} ps" >&2
    echo "   Logs:         docker compose -f ${COMPOSE_FILE} -p ${PROJECT} logs <service>" >&2
    exit 1
  fi

  sleep 5
done

# ── Summary ──────────────────────────────────────────────────────────────────
cat <<'EOF'

────────────────────────────────────────────────────────────────────────────
  OnePlatform dev-test stack is UP
────────────────────────────────────────────────────────────────────────────

  Web UI (Caddy, self-signed TLS):
    https://localhost:8443        (accept the self-signed certificate warning)
    http://localhost:8080         (redirects to HTTPS)

  Direct API access (gateway, for testing):
    http://localhost:4080/healthz
    http://localhost:4080/api/...

  Infrastructure (bound to 127.0.0.1 only):
    PostgreSQL      localhost:5532   (db: oneplatform, user: postgres)
    Redis           localhost:6479
    MinIO API       http://localhost:9100
    MinIO Console   http://localhost:9101
    Jaeger UI       http://localhost:16687
    Grafana         http://localhost:3101

  Default credentials (DEV-TEST ONLY — do not use in production):
    MinIO       user: minioadmin   pass: oneplatform_minio_dev_2024
    Grafana     user: admin        pass: admin
    PostgreSQL/Redis/service passwords are auto-generated by op-init and live
    on the op-dev-test-init-data volume (read them via:
      docker exec op-dev-test-postgres cat /data/init/db_password_app.txt)

  Note: the very first user you register via the web UI becomes the platform
  owner/admin (no email verification required in dev-test).

  Useful commands:
    Status:  docker compose -f docker/docker-compose.dev-test.yml -p op-dev-test ps
    Logs:    docker compose -f docker/docker-compose.dev-test.yml -p op-dev-test logs -f
    Stop:    ./docker/dev-test-stop.sh
────────────────────────────────────────────────────────────────────────────
EOF
