#!/bin/sh
# docker/service-entrypoint.sh
#
# Wrapper executed as the ENTRYPOINT for each application service container.
# Reads secrets generated by op-init from the init-data volume and exports
# them as environment variables before exec'ing the Node.js process.
#
# Why read from files rather than environment variables?
# Docker Compose env: blocks require plaintext values at compose-up time.
# The init-data volume approach means secrets are never visible in
# `docker inspect`, docker-compose.yml, or .env files. They exist only
# on the volume and in the process's memory after exec.
#
# SERVICE_NAME must be set in the container's environment section (e.g.
# "gateway-service"). It drives both the database alias and the private key path.
#
# Ref spec §2 "Startup Sequence", §4 "Service-to-Service Auth".

set -e

INIT_DIR="/data/init"

# ── Guard: op-init must have completed ──────────────────────────────────────
if [ ! -f "$INIT_DIR/ready" ]; then
  echo "[service-entrypoint] FATAL: op-init has not completed ($INIT_DIR/ready missing)." >&2
  echo "[service-entrypoint] Ensure op-init ran successfully before starting services." >&2
  exit 1
fi

# ── Helper: read a secret file, stripping whitespace ─────────────────────────
read_secret() {
  local file="$1"
  if [ ! -f "$file" ]; then
    echo "[service-entrypoint] FATAL: Secret file not found: $file" >&2
    exit 1
  fi
  tr -d '[:space:]' < "$file"
}

# ── Shared secrets ────────────────────────────────────────────────────────────
# Separate assignment from export so the shell's exit status reflects the
# read_secret call, not the export. Inline `export foo=$(...)` masks a non-zero
# exit from the subshell on POSIX sh — the guard below would never trigger.
OP_JWT_SECRET=$(read_secret "$INIT_DIR/jwt.secret")
[ -n "$OP_JWT_SECRET" ] || { echo "[service-entrypoint] FATAL: jwt.secret is empty" >&2; exit 1; }
export OP_JWT_SECRET

OP_MASTER_KEY=$(read_secret "$INIT_DIR/master.key")
[ -n "$OP_MASTER_KEY" ] || { echo "[service-entrypoint] FATAL: master.key is empty" >&2; exit 1; }
export OP_MASTER_KEY

OP_CURSOR_SECRET=$(read_secret "$INIT_DIR/cursor.secret")
[ -n "$OP_CURSOR_SECRET" ] || { echo "[service-entrypoint] FATAL: cursor.secret is empty" >&2; exit 1; }
export OP_CURSOR_SECRET
# Bootstrap token may be absent if bootstrap already completed on a previous run.
# Do not fail if missing — the Auth Service handles the absent-token case.
if [ -f "$INIT_DIR/bootstrap.token" ]; then
  export OP_BOOTSTRAP_TOKEN=$(tr -d '[:space:]' < "$INIT_DIR/bootstrap.token")
else
  export OP_BOOTSTRAP_TOKEN=""
fi

# ── Per-service database connection URL ──────────────────────────────────────
# Derive the service short name (e.g. "gateway" from "gateway-service").
# This must match the password file naming convention in op-init and the
# pgbouncer.ini database alias naming convention (oneplatform_<service>).
SERVICE_SHORT="${SERVICE_NAME%-service}"

DB_PASSWORD=$(read_secret "$INIT_DIR/db_password_${SERVICE_SHORT}.txt")
# Route through PgBouncer (port 5433) using the per-service database alias.
# Each alias in pgbouncer.ini maps to the correct Postgres role automatically.
export OP_DATABASE_URL="postgres://${SERVICE_SHORT}_service_role:${DB_PASSWORD}@pgbouncer:5433/oneplatform_${SERVICE_SHORT}"

# ── Per-service Redis connection URL ──────────────────────────────────────────
REDIS_PASSWORD=$(read_secret "$INIT_DIR/redis_password_${SERVICE_SHORT}.txt")
export OP_REDIS_URL="redis://:${REDIS_PASSWORD}@redis:6379"

# ── Ed25519 private key path ─────────────────────────────────────────────────
# Services that need to make outbound service-to-service calls sign tokens with
# their private key. The path is exposed as OP_SERVICE_PRIVATE_KEY_PATH so
# service code can read it at startup.
PRIVATE_KEY_PATH="$INIT_DIR/keys/${SERVICE_NAME}/private.pem"
if [ -f "$PRIVATE_KEY_PATH" ]; then
  export OP_SERVICE_PRIVATE_KEY_PATH="$PRIVATE_KEY_PATH"
else
  echo "[service-entrypoint] WARNING: Private key not found at $PRIVATE_KEY_PATH" >&2
  echo "[service-entrypoint] Service-to-service calls will fail signature generation." >&2
fi

echo "[service-entrypoint] Secrets loaded for ${SERVICE_NAME}. Starting node..."

# exec replaces the shell process so Node.js is PID 1 (receives SIGTERM correctly)
exec node dist/index.js
