/**
 * AuthProvider interface and supporting types.
 *
 * An AuthProvider extends the platform's authentication system with a custom
 * OAuth2, SAML, OIDC, LDAP, or proprietary protocol integration. The Auth Service
 * drives the OAuth dance and calls the plugin for URL-building and callback-handling.
 *
 * Security note: The Auth Service validates the state parameter (CSRF check) internally
 * before calling handleCallback. The plugin never receives the raw state value.
 */

import type {
  TenantContext,
  PluginLogger,
  CacheAccessor,
  FetchProxy,
  CredentialAccessor,
} from "./context.js";
import type { AuthProviderMetadata } from "./metadata.js";

export interface AuthOptions {
  /** The platform's OAuth callback URL. Must be included verbatim in the authorization URL. */
  redirectUri: string;

  /** OAuth scopes to request. If omitted, the provider's default scopes apply. */
  scopes?: string[];

  /** Provider-specific query parameters to append to the authorization URL. */
  additionalParams?: Record<string, string>;
}

export interface CallbackParams {
  /**
   * The authorization code from the OAuth provider.
   * For SAML flows, this is the decoded assertion value after base64 decoding.
   */
  code: string;

  /** Set if the provider returned an error in the callback. */
  error?: string;

  /** Human-readable description of the error, if present. */
  errorDescription?: string;
}

export interface AuthContext {
  tenant: TenantContext;
  logger: PluginLogger;

  /**
   * Cache accessor for storing PKCE code verifiers, nonces, or other
   * short-lived values needed across the two legs of the auth flow.
   * Use TTLs of 300 seconds (5 minutes) for these values.
   */
  cache: CacheAccessor;

  /**
   * Proxied HTTP fetch for making outbound requests during the auth flow
   * (e.g., exchanging an authorization code for tokens at the provider's
   * token endpoint). Only URLs declared in the plugin manifest's
   * requiredExternalUrls are permitted.
   */
  fetch: FetchProxy;

  /**
   * Access to the plugin instance's bound credentials (client secrets,
   * API keys, etc.) needed for OAuth code exchange and token operations.
   * Never log or cache credential values — the platform manages rotation.
   */
  credentials: CredentialAccessor;
}

export interface AuthResult {
  accessToken: string;
  refreshToken?: string;

  /** ISO 8601 expiry time for the access token. */
  expiresAt?: string;

  /** Raw claims from the identity provider. Used by mapClaimsToRoles(). */
  claims: Record<string, unknown>;

  /** Platform RBAC role names assigned to this user, as returned by mapClaimsToRoles(). */
  platformRoles: string[];

  /** The user's stable ID in the external identity provider. */
  providerUserId: string;
}

export interface TokenValidation {
  valid: boolean;
  claims?: Record<string, unknown>;
  expiresAt?: string;
  error?: string;
}

export interface TokenPair {
  accessToken: string;
  refreshToken?: string;
  expiresAt?: string;
}

export interface AuthProvider {
  metadata(): AuthProviderMetadata;

  /**
   * Build the authorization URL that the browser navigates to.
   * This method is synchronous — it should not make network calls.
   *
   * @param state An opaque, cryptographically random string generated by the Auth Service.
   *              Include this in the authorization URL as the `state` query parameter.
   *              The Auth Service will verify it matches when the callback arrives.
   * @param options Platform-provided callback configuration.
   * @returns The full authorization URL to redirect the browser to.
   */
  getAuthorizationUrl(state: string, options: AuthOptions): string;

  /**
   * Handle the OAuth callback. Exchange the authorization code for tokens.
   *
   * The Auth Service has already verified the state parameter (CSRF check) before
   * calling this method. The plugin should exchange the code for tokens and return
   * an AuthResult. Never call external token validation URLs from this method —
   * the platform considers the tokens valid if they arrive in the provider's callback.
   *
   * @throws PluginAuthError if the code exchange fails (e.g., expired code, bad credentials).
   */
  handleCallback(params: CallbackParams, context: AuthContext): Promise<AuthResult>;

  /**
   * Validate an access token with the external provider.
   * Only implement if AuthProviderMetadata.supportsTokenValidation is true.
   * Called on API requests to verify the token has not been revoked externally.
   *
   * @returns TokenValidation with valid=false if the token is expired or revoked.
   *          Do not throw for invalid tokens — return valid=false.
   * @throws PluginAuthError only for unrecoverable errors (e.g., provider unreachable).
   */
  validateToken?(token: string, context: AuthContext): Promise<TokenValidation>;

  /**
   * Exchange a refresh token for a new access token.
   * Only implement if AuthProviderMetadata.supportsTokenRefresh is true.
   *
   * Use context.cache.lock() to prevent concurrent refreshes for the same user.
   *
   * @throws PluginAuthError if the refresh token is expired or revoked.
   */
  refreshToken?(refreshToken: string, context: AuthContext): Promise<TokenPair>;

  /**
   * Map external identity provider claims to OnePlatform RBAC role names.
   * Called during login and on every token refresh to keep role assignments current.
   *
   * Returns an array of platform role name strings. Roles that do not exist in
   * the platform are ignored. An empty array means the user has no roles (they
   * can still log in but will have no permissions).
   *
   * This method is synchronous and must not make network calls.
   */
  mapClaimsToRoles(claims: Record<string, unknown>): string[];
}
