/**
 * Layout <-> React code converter.
 *
 * layoutToReactCode: deterministic — same layout always produces the same
 * string. Generated code is idiomatic and importable into the Monaco editor
 * without modification.
 *
 * reactCodeToLayout: best-effort parser. It recognises the exact output
 * format produced by layoutToReactCode and reconstructs the layout. Code that
 * has been edited by hand may not round-trip perfectly, which is intentional —
 * the builder is a starting point, not a constraint.
 *
 * Neither function has side effects or external dependencies, so they can be
 * tested in isolation without a browser environment.
 */

import { nanoid } from "nanoid";
import type { AppLayout, LayoutRow, LayoutColumn, PlacedComponent, DataBinding } from "./types.js";
import { getPaletteEntry } from "./palette-registry.js";

// ---------------------------------------------------------------------------
// Component imports — SDK components
// ---------------------------------------------------------------------------

const SDK_COMPONENTS = new Set([
  "DataTable",
  "StatCard",
  "StatusBadge",
  "FilterBar",
  "EmptyState",
  "PageHeader",
  "DetailPanel",
]);

// Chart, form, interactive, and progress components are rendered by the
// builder's preview layer and emitted as self-contained JSX in generated code.
// They are NOT SDK components — the generated file imports them from a separate
// builder-components package that developers can swap for their own library.
const BUILDER_COMPONENTS = new Set([
  "BarChart",
  "LineChart",
  "PieChart",
  "AreaChart",
  "KPICard",
  "TextInput",
  "NumberInput",
  "DatePicker",
  "SelectInput",
  "CheckboxGroup",
  "ActionButton",
  "LinkButton",
  "ProgressBar",
  "MetricGauge",
]);

// ---------------------------------------------------------------------------
// layoutToReactCode
// ---------------------------------------------------------------------------

/**
 * Generates a complete React component file (App.tsx) from an AppLayout.
 *
 * The generated code:
 * - Imports only the SDK components actually used in the layout
 * - Uses Tailwind 12-column grid classes for the row/column structure
 * - Emits data-binding comments so developers know where to wire up data
 * - Produces valid TypeScript with no implicit `any`
 */
export function layoutToReactCode(layout: AppLayout): string {
  const usedSdkComponents = collectUsedSdkComponents(layout);
  const usedBuilderComponents = collectUsedBuilderComponents(layout);

  const lines: string[] = [];

  // Imports
  lines.push(`import React from "react";`);

  if (usedSdkComponents.size > 0) {
    lines.push(
      `import { ${[...usedSdkComponents].sort().join(", ")} } from "@oneplatform/app-sdk";`,
    );
  }

  if (usedBuilderComponents.size > 0) {
    // Chart, form, interactive, and progress components ship separately from
    // the core SDK. Replace this import path with your own component library.
    lines.push(
      `import { ${[...usedBuilderComponents].sort().join(", ")} } from "@oneplatform/builder-components";`,
    );
  }

  // Custom HTML/Markdown blocks are inlined — no import needed.

  lines.push("");
  lines.push("// Generated by OnePlatform App Builder — edit freely");
  lines.push("");

  // Component function
  lines.push("export function App() {");
  lines.push("  return (");
  lines.push(`    <div className="flex flex-col gap-4 p-4">`);

  for (const row of layout.rows) {
    lines.push(...renderRow(row, 6));
  }

  lines.push("    </div>");
  lines.push("  );");
  lines.push("}");

  return lines.join("\n");
}

/**
 * Strip characters that cannot appear in a safe HTML attribute value.
 * Row and column IDs come from nanoid (already alphanumeric + hyphens) but
 * we guard here in case IDs ever come from untrusted sources such as parsed
 * user code returned by reactCodeToLayout.
 */
function sanitizeId(id: string): string {
  return id.replace(/[^a-zA-Z0-9_-]/g, "");
}

/**
 * Remove script tags, iframes, and inline event handlers from HTML before
 * embedding it in generated TSX. The generated file is code the developer
 * will review, but a malicious payload could trick them into deploying XSS.
 */
function sanitizeHtmlForCodeGen(html: string): string {
  return html
    .replace(/<script\b[^<]*(?:(?!<\/script>)<[^<]*)*<\/script>/gi, "")
    .replace(/<iframe\b[^>]*>[\s\S]*?<\/iframe>/gi, "")
    .replace(/\bon\w+\s*=\s*(?:"[^"]*"|'[^']*'|[^\s>]*)/gi, "");
}

function renderRow(row: LayoutRow, indent: number): string[] {
  const pad = " ".repeat(indent);
  const lines: string[] = [];

  const heightStyle = row.height !== undefined ? ` style={{ height: "${row.height}" }}` : "";

  // Each row is a CSS grid div with the standard 12-column grid.
  // IDs are sanitized to prevent attribute injection from parsed user code.
  lines.push(
    `${pad}<div className="grid grid-cols-12 gap-4"${heightStyle} data-row-id="${sanitizeId(row.id)}">`,
  );

  for (const col of row.columns) {
    lines.push(...renderColumn(col, indent + 2));
  }

  lines.push(`${pad}</div>`);
  return lines;
}

function renderColumn(col: LayoutColumn, indent: number): string[] {
  const pad = " ".repeat(indent);
  const lines: string[] = [];
  const span = `col-span-${col.width}`;

  lines.push(`${pad}<div className="${span}" data-col-id="${sanitizeId(col.id)}">`);

  if (col.component !== undefined) {
    lines.push(...renderComponent(col.component, indent + 2));
  }

  lines.push(`${pad}</div>`);
  return lines;
}

function renderComponent(component: PlacedComponent, indent: number): string[] {
  const pad = " ".repeat(indent);
  const lines: string[] = [];

  if (component.dataBinding !== undefined) {
    lines.push(
      `${pad}{/* Data binding: entityType="${component.dataBinding.entityType}" */}`,
    );
    lines.push(`${pad}{/* fieldMap: ${JSON.stringify(component.dataBinding.fieldMap)} */}`);
  }

  // Custom blocks render raw content
  if (component.type === "HtmlBlock") {
    const html = String(component.props["html"] ?? "");
    // Strip scripts, iframes, and event handlers before embedding so that a
    // developer reviewing the generated file isn't silently shipping XSS.
    const safeHtml = sanitizeHtmlForCodeGen(html);
    lines.push(`${pad}{/* WARNING: User-supplied HTML content — review before deploying */}`);
    lines.push(`${pad}<div dangerouslySetInnerHTML={{ __html: ${JSON.stringify(safeHtml)} }} />`);
    return lines;
  }

  if (component.type === "MarkdownBlock") {
    // Runtime markdown rendering is the app developer's responsibility;
    // we emit a pre-formatted block as a starting point.
    const content = String(component.props["content"] ?? "");
    lines.push(`${pad}<pre className="whitespace-pre-wrap">${escapeJsxText(content)}</pre>`);
    return lines;
  }

  // SDK components — emit as JSX with props
  const styleAttr = buildStyleAttr(component.styles);
  const propsStr = buildPropsString(component.props, indent + 2);
  const tag = component.type;

  if (propsStr === "") {
    lines.push(`${pad}<${tag}${styleAttr} />`);
  } else {
    lines.push(`${pad}<${tag}`);
    lines.push(propsStr);
    if (styleAttr !== "") {
      lines.push(`${pad}  ${styleAttr.trim()}`);
    }
    lines.push(`${pad}/>`);
  }

  return lines;
}

/** Serialises props Record to JSX attribute lines. */
function buildPropsString(props: Record<string, unknown>, indent: number): string {
  const pad = " ".repeat(indent);
  const entries = Object.entries(props);
  if (entries.length === 0) return "";

  return entries
    .map(([key, value]) => {
      if (typeof value === "string") return `${pad}${key}=${JSON.stringify(value)}`;
      if (typeof value === "boolean") return value ? `${pad}${key}` : `${pad}${key}={false}`;
      if (typeof value === "number") return `${pad}${key}={${value}}`;
      // Arrays and objects — emit as JSX expression with JSON literal
      return `${pad}${key}={${JSON.stringify(value)}}`;
    })
    .join("\n");
}

function buildStyleAttr(styles: Record<string, string> | undefined): string {
  if (styles === undefined || Object.keys(styles).length === 0) return "";
  const entries = Object.entries(styles)
    .map(([k, v]) => `${k}: "${v}"`)
    .join(", ");
  return ` style={{ ${entries} }}`;
}

function escapeJsxText(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/\{/g, "&#123;")
    .replace(/\}/g, "&#125;");
}

function collectUsedSdkComponents(layout: AppLayout): Set<string> {
  const result = new Set<string>();
  for (const row of layout.rows) {
    for (const col of row.columns) {
      if (col.component && SDK_COMPONENTS.has(col.component.type)) {
        result.add(col.component.type);
      }
    }
  }
  return result;
}

function collectUsedBuilderComponents(layout: AppLayout): Set<string> {
  const result = new Set<string>();
  for (const row of layout.rows) {
    for (const col of row.columns) {
      if (col.component && BUILDER_COMPONENTS.has(col.component.type)) {
        result.add(col.component.type);
      }
    }
  }
  return result;
}

// ---------------------------------------------------------------------------
// reactCodeToLayout
// ---------------------------------------------------------------------------

/**
 * Parse a React file generated by layoutToReactCode back into an AppLayout.
 *
 * Strategy: locate all `data-row-id` and `data-col-id` marker attributes
 * embedded by the generator, then extract the content between them.
 *
 * The algorithm walks the code linearly:
 *  1. Find each row opening tag (contains data-row-id) and record its row id.
 *  2. Find each column tag (contains data-col-id), extract col id + span width.
 *  3. The column body is everything between the opening col div and its closing.
 *
 * This is explicitly best-effort. Code that does not contain the generator
 * markers returns a single-row, single-column layout with an HtmlBlock
 * containing the original source so nothing is lost.
 */
export function reactCodeToLayout(code: string): AppLayout {
  const lines = code.split("\n");

  const rows: LayoutRow[] = [];
  let currentRow: LayoutRow | null = null;
  let currentColId: string | null = null;
  let currentColWidth = 12;
  let colBodyLines: string[] = [];
  let inColBody = false;
  // Track nesting depth inside a column so we know when the closing </div> belongs to the column
  let colNestDepth = 0;

  for (const line of lines) {
    // Row opening: <div ... data-row-id="xxx" ...>
    const rowMatch = /data-row-id="([^"]+)"/.exec(line);
    if (rowMatch !== null && line.includes("<div")) {
      // Flush any previous row
      if (currentRow !== null) {
        rows.push(currentRow);
      }
      currentRow = { id: rowMatch[1]!, columns: [] };
      currentColId = null;
      inColBody = false;
      continue;
    }

    if (currentRow === null) continue;

    // Column opening: <div className="col-span-N" data-col-id="xxx">
    const colMatch = /data-col-id="([^"]+)"/.exec(line);
    if (colMatch !== null && line.includes("<div")) {
      // Flush previous column body
      if (currentColId !== null && inColBody) {
        const component = parseComponentFromColumnBody(colBodyLines.join("\n").trim());
        const col: LayoutColumn = component !== null
          ? { id: currentColId, width: currentColWidth, component }
          : { id: currentColId, width: currentColWidth };
        currentRow.columns.push(col);
      }
      currentColId = colMatch[1]!;
      const spanMatch = /col-span-(\d+)/.exec(line);
      currentColWidth = spanMatch !== null ? parseInt(spanMatch[1]!, 10) : 12;
      colBodyLines = [];
      inColBody = true;
      colNestDepth = 0;
      continue;
    }

    if (!inColBody || currentColId === null) continue;

    // Track nesting so we know when the </div> closes the column
    const openDivs = (line.match(/<div/g) ?? []).length;
    const closeDivs = (line.match(/<\/div>/g) ?? []).length;

    // Column-closing </div> when nesting returns to -1 (we started at 0 inside the col)
    colNestDepth += openDivs - closeDivs;

    if (colNestDepth < 0) {
      // This </div> closes the column
      inColBody = false;
      if (currentRow !== null) {
        const component = parseComponentFromColumnBody(colBodyLines.join("\n").trim());
        const col: LayoutColumn = component !== null
          ? { id: currentColId, width: currentColWidth, component }
          : { id: currentColId, width: currentColWidth };
        currentRow.columns.push(col);
      }
      currentColId = null;
      colBodyLines = [];
      colNestDepth = 0;
    } else {
      colBodyLines.push(line);
    }
  }

  // Flush last row
  if (currentRow !== null && currentRow.columns.length > 0) {
    rows.push(currentRow);
  }

  // If we couldn't parse any rows, fall back to wrapping the raw code
  if (rows.length === 0) {
    return createFallbackLayout(code);
  }

  return { rows };
}

function parseComponentFromColumnBody(body: string): PlacedComponent | null {
  if (body.trim() === "") return null;

  // HtmlBlock: dangerouslySetInnerHTML
  const htmlMatch = /dangerouslySetInnerHTML=\{\{\s*__html:\s*(["'`])([\s\S]*?)\1\s*\}\}/.exec(body);
  if (htmlMatch !== null) {
    return {
      id: nanoid(),
      type: "HtmlBlock",
      props: { html: unescapeJsonString(htmlMatch[2]!) },
    };
  }

  // MarkdownBlock: <pre ... >content</pre>
  const mdMatch = /<pre[^>]*>([\s\S]*?)<\/pre>/.exec(body);
  if (mdMatch !== null) {
    return {
      id: nanoid(),
      type: "MarkdownBlock",
      props: { content: unescapeJsxText(mdMatch[1]!) },
    };
  }

  // SDK / generic JSX tag
  const tagMatch = /<([A-Z][A-Za-z0-9]*)(\s[\s\S]*?)?\s*\/>/.exec(body);
  if (tagMatch !== null) {
    const type = tagMatch[1]!;
    const attrsStr = tagMatch[2] ?? "";
    const props = parseJsxProps(attrsStr);
    const entry = getPaletteEntry(type);
    return {
      id: nanoid(),
      type,
      props: { ...(entry?.defaultProps ?? {}), ...props },
    };
  }

  return null;
}

/**
 * Naive JSX props parser. Handles string, number, boolean, and JSON literal
 * expressions — the same forms the generator emits. Does not handle nested
 * JSX, function props, or template literals.
 */
function parseJsxProps(attrsStr: string): Record<string, unknown> {
  const result: Record<string, unknown> = {};

  // String: key="value"
  const stringPattern = /(\w[\w-]*)="([^"]*)"/g;
  let m: RegExpExecArray | null;
  while ((m = stringPattern.exec(attrsStr)) !== null) {
    result[m[1]!] = m[2];
  }

  // Expression: key={value} — uses brace counting to handle nested braces
  // (e.g. key={{ nested: true }}) correctly instead of a non-greedy regex
  // which would stop at the first closing brace.
  const exprStartPattern = /(\w[\w-]*)=\{/g;
  let exprMatch: RegExpExecArray | null;
  while ((exprMatch = exprStartPattern.exec(attrsStr)) !== null) {
    const key = exprMatch[1]!;
    const contentStart = exprMatch.index + exprMatch[0].length;
    let depth = 1;
    let i = contentStart;
    while (i < attrsStr.length && depth > 0) {
      if (attrsStr[i] === "{") depth++;
      else if (attrsStr[i] === "}") depth--;
      if (depth > 0) i++;
    }
    if (depth !== 0) continue; // unbalanced — skip
    const expr = attrsStr.slice(contentStart, i).trim();
    // Boolean false
    if (expr === "false") { result[key] = false; continue; }
    // Try JSON parse for number / array / object
    try {
      result[key] = JSON.parse(expr);
    } catch {
      // Not parseable — keep as raw string
      result[key] = expr;
    }
  }

  // Bare boolean: key (no value)
  const boolPattern = /(?:^|\s)(\w[\w-]*)(?=\s|$)(?!=)/g;
  while ((m = boolPattern.exec(attrsStr)) !== null) {
    if (!(m[1]! in result)) {
      result[m[1]!] = true;
    }
  }

  return result;
}

function unescapeJsonString(raw: string): string {
  try {
    // The generator uses JSON.stringify, so the value is a JSON string literal
    return JSON.parse(`"${raw}"`);
  } catch {
    return raw;
  }
}

function unescapeJsxText(text: string): string {
  return text
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&#123;/g, "{")
    .replace(/&#125;/g, "}");
}

function createFallbackLayout(code: string): AppLayout {
  return {
    rows: [
      {
        id: nanoid(),
        columns: [
          {
            id: nanoid(),
            width: 12,
            component: {
              id: nanoid(),
              type: "HtmlBlock",
              props: {
                html: `<pre><code>${escapeJsxText(code)}</code></pre>`,
              },
            },
          },
        ],
      },
    ],
  };
}

// ---------------------------------------------------------------------------
// Data binding code helper
// ---------------------------------------------------------------------------

/**
 * Emit the fetch + pass-through code for a data binding.
 * This is used by the builder's "copy snippet" button — not part of the main
 * generated output, which only adds comments.
 */
export function dataBindingToHookSnippet(binding: DataBinding, componentProp: string): string {
  return [
    `// Bind "${binding.entityType}" data to ${componentProp}`,
    `const { data: ${binding.entityType}Data } = useQuery({`,
    `  queryKey: ["${binding.entityType}"],`,
    `  queryFn: ({ signal }) => client.get(\`/v1/entities/${binding.entityType}\`, undefined, { signal }),`,
    `});`,
    ``,
    `// Map fields: ${JSON.stringify(binding.fieldMap)}`,
    `const ${componentProp} = (${binding.entityType}Data?.data ?? []).map((item: Record<string, unknown>) => ({`,
    ...Object.entries(binding.fieldMap).map(([prop, field]) => `  ${prop}: item[${JSON.stringify(field)}],`),
    `}));`,
  ].join("\n");
}
