// JWT issuance, verification, and revocation for access tokens.
// Refresh token rotation and family-detection replay logic.
//
// Access tokens support two signing algorithms selected by OP_JWT_ALGORITHM:
//   HS256 (default) — symmetric, signed and verified with OP_JWT_SECRET
//   EdDSA          — asymmetric Ed25519; signed with OP_JWT_PRIVATE_KEY,
//                    verified with OP_JWT_PUBLIC_KEY (base64-encoded DER)
//
// HS256 remains the default so existing deployments that have not generated
// an Ed25519 key pair continue to work without any configuration change.
//
// Refresh tokens are opaque 32-byte random hex strings stored in Redis.
// The L2 design (§6.3, §6.4, §6.6) specifies the exact shape of every
// operation here.

import { randomBytes, randomUUID, createPublicKey, createPrivateKey } from "crypto";
import { SignJWT, jwtVerify, type JWTPayload, type KeyLike } from "jose";
import type { Redis } from "ioredis";
import type pg from "pg";
import type { JwtClaims, UserForToken } from "./types.js";
import {
  TokenReplayDetectedError,
  SessionRevokedError,
} from "./errors.js";
import { UnauthorizedError } from "@oneplatform/core";

// ---------------------------------------------------------------------------
// Scope resolution
// ---------------------------------------------------------------------------

// The complete set of scopes the platform supports (from L2 design §4.4).
// execution:read must pair with execution:run so GET endpoints on the
// execution service are accessible to all roles that can trigger executions.
const ALL_SCOPES: readonly string[] = [
  "data:read",
  "data:write",
  "ontology:read",
  "ontology:write",
  "pipelines:read",
  "pipelines:trigger",
  "pipelines:manage",
  "apps:read",
  "apps:deploy",
  "apps:manage",
  "plugins:read",
  "plugins:manage",
  "users:read",
  "users:manage",
  "logs:read",
  "logs:export",
  "audit:read",
  "webhooks:manage",
  "execution:read",
  "execution:run",
  "admin",
] as const;

// Built-in role → scope mappings (mirrors seed SQL in L2 design §8.1).
// Custom roles are looked up at query time via the DB; these are the
// predefined fallbacks that must always work even before DB data is loaded.
const PREDEFINED_ROLE_SCOPES: Readonly<Record<string, readonly string[]>> = {
  "platform-admin": ["admin"],
  "tenant-admin": [
    "data:read", "data:write", "ontology:read", "ontology:write",
    "pipelines:manage", "apps:manage", "apps:deploy", "apps:read",
    "execution:read", "execution:run", "plugins:read", "plugins:manage",
    "users:read", "users:manage", "logs:read", "logs:export",
    "audit:read", "webhooks:manage",
  ],
  developer: [
    "data:read", "data:write", "ontology:read", "pipelines:manage",
    "apps:manage", "apps:deploy", "apps:read", "execution:read", "execution:run",
    "plugins:read", "logs:read", "audit:read",
  ],
  editor: [
    "data:read", "data:write", "ontology:read", "pipelines:manage",
    "apps:manage", "apps:read", "execution:read", "logs:read", "audit:read",
  ],
  viewer: [
    "data:read", "ontology:read", "pipelines:read", "apps:read", "logs:read",
  ],
};

export function resolveScopes(roles: string[]): string[] {
  const union = new Set<string>();
  for (const role of roles) {
    const scopes = PREDEFINED_ROLE_SCOPES[role];
    if (scopes !== undefined) {
      for (const s of scopes) union.add(s);
    }
    // Custom role scopes are injected at JWT issuance by the caller
    // by augmenting the roles list with their DB-fetched scopes, or
    // via the customRoleScopes parameter in issueAccessToken.
  }
  // 'admin' short-circuits to the full scope list
  if (union.has("admin")) return [...ALL_SCOPES];
  return Array.from(union);
}

// ---------------------------------------------------------------------------
// Supported signing algorithms
// ---------------------------------------------------------------------------

export type JwtAlgorithm = "HS256" | "EdDSA";

// ---------------------------------------------------------------------------
// Configuration helpers
// ---------------------------------------------------------------------------

/**
 * Returns the configured signing algorithm.
 * Defaults to HS256 so deployments without OP_JWT_ALGORITHM set continue
 * to use the existing symmetric path without any reconfiguration.
 */
export function getJwtAlgorithm(): JwtAlgorithm {
  const raw = process.env["OP_JWT_ALGORITHM"];
  if (raw === undefined || raw === "HS256") return "HS256";
  if (raw === "EdDSA") return "EdDSA";
  throw new Error(
    `Unsupported OP_JWT_ALGORITHM "${raw}". Supported values: HS256, EdDSA.`
  );
}

function getJwtSecret(): Uint8Array {
  const secret = process.env["OP_JWT_SECRET"];
  if (!secret) {
    throw new Error(
      "OP_JWT_SECRET is required but not set. " +
        "The secret is generated by op-init and must be present at startup."
    );
  }
  return new TextEncoder().encode(secret);
}

/**
 * Loads and caches the Ed25519 signing key derived from OP_JWT_PRIVATE_KEY.
 * OP_JWT_PRIVATE_KEY is the PKCS#8 PEM private key as a base64-encoded string
 * (base64 of the raw PEM bytes, not just the key material).
 *
 * We decode → PEM → native KeyObject once at call time and return it.
 * The caller is responsible for caching the result if desired.
 */
async function loadEdDsaPrivateKey(): Promise<KeyLike> {
  const raw = process.env["OP_JWT_PRIVATE_KEY"];
  if (!raw) {
    throw new Error(
      "OP_JWT_PRIVATE_KEY is required when OP_JWT_ALGORITHM=EdDSA. " +
        "Generate a key pair with: scripts/generate-jwt-keys.sh"
    );
  }
  // OP_JWT_PRIVATE_KEY is the base64-encoded PEM so it survives env var injection
  // as a single-line value. Decode it back to the PEM string.
  const pem = Buffer.from(raw, "base64").toString("utf8");
  const keyObject = createPrivateKey(pem);
  // jose requires a KeyLike (CryptoKey or KeyObject). Node.js KeyObject satisfies
  // the KeyLike interface directly when passed to jose's SignJWT.
  return keyObject as unknown as KeyLike;
}

/**
 * Loads the Ed25519 verification key from OP_JWT_PUBLIC_KEY.
 * OP_JWT_PUBLIC_KEY is the SPKI PEM public key, base64-encoded.
 */
async function loadEdDsaPublicKey(): Promise<KeyLike> {
  const raw = process.env["OP_JWT_PUBLIC_KEY"];
  if (!raw) {
    throw new Error(
      "OP_JWT_PUBLIC_KEY is required when OP_JWT_ALGORITHM=EdDSA. " +
        "Generate a key pair with: scripts/generate-jwt-keys.sh"
    );
  }
  const pem = Buffer.from(raw, "base64").toString("utf8");
  const keyObject = createPublicKey(pem);
  return keyObject as unknown as KeyLike;
}

function getJwtExpirySeconds(): number {
  const raw = process.env["OP_JWT_EXPIRY_SECONDS"];
  return raw !== undefined ? parseInt(raw, 10) : 900;
}

function getRefreshTokenTtlSeconds(): number {
  const raw = process.env["OP_REFRESH_TOKEN_TTL_SECONDS"];
  return raw !== undefined ? parseInt(raw, 10) : 604_800; // 7 days
}

// ---------------------------------------------------------------------------
// JWKS helpers — converts an Ed25519 public key to JWK format for the
// /.well-known/jwks.json endpoint consumed by downstream verifiers.
// ---------------------------------------------------------------------------

export interface JwkPublicKey {
  kty: "OKP";
  crv: "Ed25519";
  x: string;
  use: "sig";
  alg: "EdDSA";
  kid: string;
}

/**
 * Exports the currently-configured Ed25519 public key as a JWK.
 * Returns null when the algorithm is HS256 (symmetric keys have no JWKS).
 *
 * The `kid` value is the base64url-encoded first 8 bytes of the raw public
 * key material — stable across restarts for the same key pair, short enough
 * to be practical as a cache/rotation identifier.
 */
export async function exportPublicKeyAsJwk(): Promise<JwkPublicKey | null> {
  if (getJwtAlgorithm() !== "EdDSA") return null;

  const raw = process.env["OP_JWT_PUBLIC_KEY"];
  if (!raw) return null;

  const pem = Buffer.from(raw, "base64").toString("utf8");
  const keyObject = createPublicKey(pem);

  // Export the raw 32-byte Ed25519 public key from the SubjectPublicKeyInfo DER
  // encoding. The last 32 bytes of the DER are the key material itself.
  const der = keyObject.export({ type: "spki", format: "der" });
  const keyMaterial = der.slice(der.length - 32);
  const x = keyMaterial.toString("base64url");
  // kid = first 8 bytes of key material as base64url — short, stable identifier
  const kid = keyMaterial.slice(0, 8).toString("base64url");

  return { kty: "OKP", crv: "Ed25519", x, use: "sig", alg: "EdDSA", kid };
}

// ---------------------------------------------------------------------------
// Refresh token Redis payload
// ---------------------------------------------------------------------------

interface RefreshTokenPayload {
  userId: string;
  tenantId: string;
  sessionId: string;
  jti: string;
  familyId: string;
}

// ---------------------------------------------------------------------------
// Service interface
// ---------------------------------------------------------------------------

export interface TokenService {
  issueAccessToken(user: UserForToken): Promise<string>;
  issueRefreshToken(
    userId: string,
    tenantId: string,
    sessionId: string,
    familyId: string
  ): Promise<{ token: string; jti: string }>;
  verifyAccessToken(token: string): Promise<JwtClaims | null>;
  revokeAccessToken(jti: string, expUnixSeconds: number): Promise<void>;
  rotateRefreshToken(oldToken: string): Promise<{
    accessToken: string;
    refreshToken: string;
    expiresIn: number;
  }>;
}

export interface TokenServiceDeps {
  redis: Redis;
  db: pg.Pool;
}

export function createTokenService(deps: TokenServiceDeps): TokenService {
  const { redis, db } = deps;

  // -------------------------------------------------------------------------
  // Access token issuance
  // -------------------------------------------------------------------------

  async function issueAccessToken(user: UserForToken): Promise<string> {
    const expirySeconds = getJwtExpirySeconds();
    const now = Math.floor(Date.now() / 1000);
    const algorithm = getJwtAlgorithm();

    // resolveScopes handles predefined roles; callers with custom roles pass
    // them with scopes already injected into the roles array or rely on the
    // predefined mapping for standard role names.
    const scopes = resolveScopes(user.roles);

    const builder = new SignJWT({
      sub: user.id,
      tid: user.tenantId,
      roles: user.roles,
      scopes,
      ev: user.emailVerified,
      // The 'unverified' flag signals to the Gateway to downgrade role scope
      // for users who registered with email verification required.
      unverified: !user.emailVerified,
      jti: randomUUID(),
    } satisfies Omit<JwtClaims, "iat" | "exp">)
      .setProtectedHeader({ alg: algorithm })
      .setIssuedAt(now)
      .setExpirationTime(now + expirySeconds);

    if (algorithm === "EdDSA") {
      const privateKey = await loadEdDsaPrivateKey();
      return builder.sign(privateKey);
    }

    return builder.sign(getJwtSecret());
  }

  // -------------------------------------------------------------------------
  // Refresh token issuance
  // -------------------------------------------------------------------------

  async function issueRefreshToken(
    userId: string,
    tenantId: string,
    sessionId: string,
    familyId: string
  ): Promise<{ token: string; jti: string }> {
    const jti = randomUUID();
    const token = randomBytes(32).toString("hex");
    const ttl = getRefreshTokenTtlSeconds();

    const payload: RefreshTokenPayload = {
      userId,
      tenantId,
      sessionId,
      jti,
      familyId,
    };
    await redis.set(
      `auth:refresh:${token}`,
      JSON.stringify(payload),
      "EX",
      ttl
    );
    // Secondary index: token → familyId for replay detection.
    // Same TTL as the refresh token so it expires naturally.
    await redis.set(`auth:token-family:${token}`, familyId, "EX", ttl);
    // Family membership set: familyId → Set of token keys.
    // Using a Set avoids a full-keyspace SCAN during replay detection — SMEMBERS
    // is O(n) on the family size only, not the entire Redis keyspace.
    await redis.sadd(`auth:refresh-family:${familyId}`, token);
    // Track active tokens per user for logout-all (SADD has no TTL; cleaned on logout)
    await redis.sadd(`auth:user-sessions:${userId}`, token);
    return { token, jti };
  }

  // -------------------------------------------------------------------------
  // Access token verification
  // -------------------------------------------------------------------------

  async function verifyAccessToken(token: string): Promise<JwtClaims | null> {
    try {
      // Read the algorithm from the token header so verification works for
      // tokens issued under the old algorithm during a rolling key rotation.
      // A token's header is unauthenticated data, but the subsequent signature
      // check ensures the correct key was used — there is no algorithm confusion
      // risk here because we only accept the two known algorithms and each uses
      // completely separate key material.
      let tokenAlgorithm: JwtAlgorithm;
      try {
        const headerPart = token.split(".")[0];
        if (!headerPart) throw new Error("empty");
        const headerJson = Buffer.from(headerPart, "base64url").toString("utf8");
        const header = JSON.parse(headerJson) as { alg?: string };
        tokenAlgorithm = header.alg === "EdDSA" ? "EdDSA" : "HS256";
      } catch {
        return null;
      }

      let payload: JWTPayload;
      if (tokenAlgorithm === "EdDSA") {
        const publicKey = await loadEdDsaPublicKey();
        ({ payload } = await jwtVerify(token, publicKey, { algorithms: ["EdDSA"] }));
      } else {
        ({ payload } = await jwtVerify(token, getJwtSecret(), { algorithms: ["HS256"] }));
      }

      const claims = payload as JWTPayload & Partial<JwtClaims>;

      // Check per-JTI and per-user revocation blocklists
      const [jtiRevoked, userRevoked] = await Promise.all([
        redis.get(`revocation:${claims["jti"]}`),
        typeof claims["sub"] === "string" ? redis.get(`revocation:user:${claims["sub"]}`) : null,
      ]);
      if (jtiRevoked !== null || userRevoked !== null) return null;

      // Validate required custom claims are present and well-typed
      if (
        typeof claims["sub"] !== "string" ||
        typeof claims["tid"] !== "string" ||
        !Array.isArray(claims["roles"]) ||
        !Array.isArray(claims["scopes"]) ||
        typeof claims["ev"] !== "boolean" ||
        typeof claims["unverified"] !== "boolean" ||
        typeof claims["jti"] !== "string" ||
        typeof claims["iat"] !== "number" ||
        typeof claims["exp"] !== "number"
      ) {
        return null;
      }

      return {
        sub: claims["sub"],
        iat: claims["iat"],
        exp: claims["exp"],
        jti: claims["jti"],
        tid: claims["tid"],
        roles: claims["roles"] as string[],
        scopes: claims["scopes"] as string[],
        ev: claims["ev"],
        unverified: claims["unverified"],
      };
    } catch {
      // jose throws on invalid/expired tokens — treat all failures as null
      return null;
    }
  }

  // -------------------------------------------------------------------------
  // Access token revocation
  // -------------------------------------------------------------------------

  async function revokeAccessToken(
    jti: string,
    expUnixSeconds: number
  ): Promise<void> {
    // TTL is the token's remaining lifetime, capped at the max access token TTL.
    // When the token would have expired anyway the Redis key auto-deletes,
    // so we never accumulate stale blocklist entries.
    const remainingSeconds = expUnixSeconds - Math.floor(Date.now() / 1000);
    if (remainingSeconds <= 0) {
      // Token already expired — no need to add to blocklist
      return;
    }
    const ttl = Math.min(remainingSeconds, getJwtExpirySeconds());
    await redis.set(`revocation:${jti}`, "1", "EX", ttl);
  }

  // -------------------------------------------------------------------------
  // Refresh token rotation (L2 design §6.4)
  // -------------------------------------------------------------------------

  async function rotateRefreshToken(oldToken: string): Promise<{
    accessToken: string;
    refreshToken: string;
    expiresIn: number;
  }> {
    // Step 1: Atomic DEL — only one concurrent rotation wins
    const pipeline = redis.pipeline();
    pipeline.get(`auth:refresh:${oldToken}`);
    pipeline.del(`auth:refresh:${oldToken}`);
    const results = await pipeline.exec();

    if (!results) {
      throw new UnauthorizedError("Token rotation pipeline failed.");
    }

    const [getResult, delResult] = results;
    const rawPayload = getResult?.[1] as string | null;
    const delCount = delResult?.[1] as number;

    if (rawPayload === null || delCount === 0) {
      // Token not in Redis — check if this is a replay (old token for a
      // session whose family is still alive but the token was already rotated)
      await detectAndHandleReplay(oldToken);
      throw new UnauthorizedError("Refresh token not found or already used.");
    }

    const payload = JSON.parse(rawPayload) as RefreshTokenPayload;

    // Step 2: Verify the session still exists and get its expiry
    const sessionResult = await db.query<{
      expires_at: Date;
      revoked_at: Date | null;
    }>(
      "SELECT expires_at, revoked_at FROM auth.sessions WHERE id = $1",
      [payload.sessionId]
    );

    const session = sessionResult.rows[0];
    if (!session) {
      throw new UnauthorizedError("Session not found.");
    }
    if (session.revoked_at !== null) {
      throw new SessionRevokedError("Session has been revoked.");
    }

    const remainingMs = session.expires_at.getTime() - Date.now();
    if (remainingMs <= 0) {
      throw new UnauthorizedError("Session has expired.");
    }

    const remainingSeconds = Math.floor(remainingMs / 1000);

    // Step 3: Issue new tokens
    const newJti = randomUUID();
    const newToken = randomBytes(32).toString("hex");

    const newPayload: RefreshTokenPayload = {
      ...payload,
      jti: newJti,
    };

    // Step 4: DB transaction — update session JTI atomically, then write new
    // token to Redis only after the DB commit succeeds.
    const client = await db.connect();
    try {
      await client.query("BEGIN");
      await client.query(
        "UPDATE auth.sessions SET refresh_token_jti = $1, last_used_at = now() WHERE id = $2",
        [newJti, payload.sessionId]
      );
      await client.query("COMMIT");
    } catch (err) {
      await client.query("ROLLBACK");
      throw err;
    } finally {
      client.release();
    }

    // Write new refresh token to Redis AFTER DB commit
    await redis.set(
      `auth:refresh:${newToken}`,
      JSON.stringify(newPayload),
      "EX",
      remainingSeconds
    );
    // Secondary index for replay detection
    await redis.set(`auth:token-family:${newToken}`, payload.familyId, "EX", remainingSeconds);
    // Update family set: remove old token, add new token
    await redis.srem(`auth:refresh-family:${payload.familyId}`, oldToken);
    await redis.sadd(`auth:refresh-family:${payload.familyId}`, newToken);
    // Update user-sessions set: remove old, add new
    await redis.srem(`auth:user-sessions:${payload.userId}`, oldToken);
    await redis.sadd(`auth:user-sessions:${payload.userId}`, newToken);

    // Step 5: Fetch user for token issuance
    const userResult = await db.query<{
      id: string;
      tenant_id: string;
      roles: string[];
      email_verified: boolean;
    }>(
      "SELECT id, tenant_id, roles, email_verified FROM auth.users WHERE id = $1",
      [payload.userId]
    );

    const user = userResult.rows[0];
    if (!user) {
      throw new UnauthorizedError("User not found.");
    }

    const accessToken = await issueAccessToken({
      id: user.id,
      tenantId: user.tenant_id,
      roles: user.roles,
      emailVerified: user.email_verified,
    });

    return {
      accessToken,
      refreshToken: newToken,
      expiresIn: getJwtExpirySeconds(),
    };
  }

  // -------------------------------------------------------------------------
  // Replay detection (L2 design §6.4 — REPLAY DETECTION section)
  // -------------------------------------------------------------------------

  async function detectAndHandleReplay(oldToken: string): Promise<void> {
    // The token is NOT in Redis — it was already rotated. Look up the
    // family via a secondary Redis index (auth:token-family:{token} → familyId)
    // that we store at issuance time.
    const familyId = await redis.get(`auth:token-family:${oldToken}`);
    if (!familyId) {
      // No family index — token was never issued or TTL expired naturally.
      // Cannot determine family; fall through to UNAUTHORIZED.
      return;
    }

    // Revoke ALL sessions in this family — a replay means the attacker has
    // a prior token while the legitimate user has a newer one.
    const sessionsResult = await db.query<{ id: string }>(
      `UPDATE auth.sessions
       SET revoked_at = now(), revoked_reason = 'token_replay_detected'
       WHERE family_id = $1 AND revoked_at IS NULL
       RETURNING id`,
      [familyId]
    );

    // Delete all refresh tokens in this family from Redis.
    // We use a Redis Set keyed by familyId (auth:refresh-family:{familyId}) that
    // is maintained at issuance and rotation time. SMEMBERS is O(n) on the family
    // size — avoids a full-keyspace SCAN which would be a DoS vector on large
    // deployments (SCAN iterates every key in Redis regardless of pattern).
    const familySetKey = `auth:refresh-family:${familyId}`;
    const familyTokens = await redis.smembers(familySetKey);
    for (const token of familyTokens) {
      await redis.del(`auth:refresh:${token}`);
      await redis.del(`auth:token-family:${token}`);
    }
    await redis.del(familySetKey);

    if (sessionsResult.rowCount !== null && sessionsResult.rowCount > 0) {
      throw new TokenReplayDetectedError(
        `Token replay detected — ${sessionsResult.rowCount} session(s) in family revoked.`
      );
    }
  }

  // -------------------------------------------------------------------------

  return {
    issueAccessToken,
    issueRefreshToken,
    verifyAccessToken,
    revokeAccessToken,
    rotateRefreshToken,
  };
}

// ---------------------------------------------------------------------------
// Named export for scope resolution — used by auth-service and bootstrap-service
// ---------------------------------------------------------------------------
export { resolveScopes as resolveScopesFromRoles };

// ---------------------------------------------------------------------------
// Re-export errors that callers need
// ---------------------------------------------------------------------------
export { TokenReplayDetectedError, SessionRevokedError };
