// JWT issuance, verification, and revocation for access tokens.
// Refresh token rotation and family-detection replay logic.
//
// Access tokens are HS256 JWTs signed with OP_JWT_SECRET.
// Refresh tokens are opaque 32-byte random hex strings stored in Redis.
// The L2 design (§6.3, §6.4, §6.6) specifies the exact shape of every
// operation here.

import { randomBytes, randomUUID } from "crypto";
import { SignJWT, jwtVerify, type JWTPayload } from "jose";
import type { Redis } from "ioredis";
import type pg from "pg";
import type { JwtClaims, UserForToken } from "./types.js";
import {
  TokenReplayDetectedError,
  SessionRevokedError,
} from "./errors.js";
import { UnauthorizedError } from "@oneplatform/core";

// ---------------------------------------------------------------------------
// Scope resolution
// ---------------------------------------------------------------------------

// The complete set of scopes the platform supports (from L2 design §4.4).
// execution:read must pair with execution:run so GET endpoints on the
// execution service are accessible to all roles that can trigger executions.
const ALL_SCOPES: readonly string[] = [
  "data:read",
  "data:write",
  "ontology:read",
  "ontology:write",
  "pipelines:read",
  "pipelines:trigger",
  "pipelines:manage",
  "apps:read",
  "apps:deploy",
  "apps:manage",
  "plugins:read",
  "plugins:manage",
  "users:read",
  "users:manage",
  "logs:read",
  "webhooks:manage",
  "execution:read",
  "execution:run",
  "admin",
] as const;

// Built-in role → scope mappings (mirrors seed SQL in L2 design §8.1).
// Custom roles are looked up at query time via the DB; these are the
// predefined fallbacks that must always work even before DB data is loaded.
const PREDEFINED_ROLE_SCOPES: Readonly<Record<string, readonly string[]>> = {
  "platform-admin": ["admin"],
  "tenant-admin": [
    "data:read", "data:write", "ontology:read", "ontology:write",
    "pipelines:manage", "apps:manage", "apps:deploy", "apps:read",
    "execution:read", "execution:run", "plugins:read", "plugins:manage",
    "users:read", "users:manage", "logs:read", "webhooks:manage",
  ],
  developer: [
    "data:read", "data:write", "ontology:read", "pipelines:manage",
    "apps:manage", "apps:deploy", "apps:read", "execution:read", "execution:run",
    "plugins:read", "logs:read",
  ],
  editor: [
    "data:read", "data:write", "ontology:read", "pipelines:manage",
    "apps:manage", "apps:read", "execution:read", "logs:read",
  ],
  viewer: [
    "data:read", "ontology:read", "pipelines:read", "apps:read", "logs:read",
  ],
};

export function resolveScopes(roles: string[]): string[] {
  const union = new Set<string>();
  for (const role of roles) {
    const scopes = PREDEFINED_ROLE_SCOPES[role];
    if (scopes !== undefined) {
      for (const s of scopes) union.add(s);
    }
    // Custom role scopes are injected at JWT issuance by the caller
    // by augmenting the roles list with their DB-fetched scopes, or
    // via the customRoleScopes parameter in issueAccessToken.
  }
  // 'admin' short-circuits to the full scope list
  if (union.has("admin")) return [...ALL_SCOPES];
  return Array.from(union);
}

// ---------------------------------------------------------------------------
// Configuration helpers
// ---------------------------------------------------------------------------

function getJwtSecret(): Uint8Array {
  const secret = process.env["OP_JWT_SECRET"];
  if (!secret) {
    throw new Error(
      "OP_JWT_SECRET is required but not set. " +
        "The secret is generated by op-init and must be present at startup."
    );
  }
  return new TextEncoder().encode(secret);
}

function getJwtExpirySeconds(): number {
  const raw = process.env["OP_JWT_EXPIRY_SECONDS"];
  return raw !== undefined ? parseInt(raw, 10) : 900;
}

function getRefreshTokenTtlSeconds(): number {
  const raw = process.env["OP_REFRESH_TOKEN_TTL_SECONDS"];
  return raw !== undefined ? parseInt(raw, 10) : 604_800; // 7 days
}

// ---------------------------------------------------------------------------
// Refresh token Redis payload
// ---------------------------------------------------------------------------

interface RefreshTokenPayload {
  userId: string;
  tenantId: string;
  sessionId: string;
  jti: string;
  familyId: string;
}

// ---------------------------------------------------------------------------
// Service interface
// ---------------------------------------------------------------------------

export interface TokenService {
  issueAccessToken(user: UserForToken): Promise<string>;
  issueRefreshToken(
    userId: string,
    tenantId: string,
    sessionId: string,
    familyId: string
  ): Promise<{ token: string; jti: string }>;
  verifyAccessToken(token: string): Promise<JwtClaims | null>;
  revokeAccessToken(jti: string, expUnixSeconds: number): Promise<void>;
  rotateRefreshToken(oldToken: string): Promise<{
    accessToken: string;
    refreshToken: string;
    expiresIn: number;
  }>;
}

export interface TokenServiceDeps {
  redis: Redis;
  db: pg.Pool;
}

export function createTokenService(deps: TokenServiceDeps): TokenService {
  const { redis, db } = deps;

  // -------------------------------------------------------------------------
  // Access token issuance
  // -------------------------------------------------------------------------

  async function issueAccessToken(user: UserForToken): Promise<string> {
    const expirySeconds = getJwtExpirySeconds();
    const now = Math.floor(Date.now() / 1000);

    // resolveScopes handles predefined roles; callers with custom roles pass
    // them with scopes already injected into the roles array or rely on the
    // predefined mapping for standard role names.
    const scopes = resolveScopes(user.roles);

    return new SignJWT({
      sub: user.id,
      tid: user.tenantId,
      roles: user.roles,
      scopes,
      ev: user.emailVerified,
      // The 'unverified' flag signals to the Gateway to downgrade role scope
      // for users who registered with email verification required.
      unverified: !user.emailVerified,
      jti: randomUUID(),
    } satisfies Omit<JwtClaims, "iat" | "exp">)
      .setProtectedHeader({ alg: "HS256" })
      .setIssuedAt(now)
      .setExpirationTime(now + expirySeconds)
      .sign(getJwtSecret());
  }

  // -------------------------------------------------------------------------
  // Refresh token issuance
  // -------------------------------------------------------------------------

  async function issueRefreshToken(
    userId: string,
    tenantId: string,
    sessionId: string,
    familyId: string
  ): Promise<{ token: string; jti: string }> {
    const jti = randomUUID();
    const token = randomBytes(32).toString("hex");
    const ttl = getRefreshTokenTtlSeconds();

    const payload: RefreshTokenPayload = {
      userId,
      tenantId,
      sessionId,
      jti,
      familyId,
    };
    await redis.set(
      `auth:refresh:${token}`,
      JSON.stringify(payload),
      "EX",
      ttl
    );
    // Secondary index: token → familyId for replay detection.
    // Same TTL as the refresh token so it expires naturally.
    await redis.set(`auth:token-family:${token}`, familyId, "EX", ttl);
    // Family membership set: familyId → Set of token keys.
    // Using a Set avoids a full-keyspace SCAN during replay detection — SMEMBERS
    // is O(n) on the family size only, not the entire Redis keyspace.
    await redis.sadd(`auth:refresh-family:${familyId}`, token);
    // Track active tokens per user for logout-all (SADD has no TTL; cleaned on logout)
    await redis.sadd(`auth:user-sessions:${userId}`, token);
    return { token, jti };
  }

  // -------------------------------------------------------------------------
  // Access token verification
  // -------------------------------------------------------------------------

  async function verifyAccessToken(token: string): Promise<JwtClaims | null> {
    try {
      const { payload } = await jwtVerify(token, getJwtSecret(), {
        algorithms: ["HS256"],
      });

      const claims = payload as JWTPayload & Partial<JwtClaims>;

      // Check revocation blocklist
      const revoked = await redis.get(`revocation:${claims["jti"]}`);
      if (revoked !== null) return null;

      // Validate required custom claims are present and well-typed
      if (
        typeof claims["sub"] !== "string" ||
        typeof claims["tid"] !== "string" ||
        !Array.isArray(claims["roles"]) ||
        !Array.isArray(claims["scopes"]) ||
        typeof claims["ev"] !== "boolean" ||
        typeof claims["unverified"] !== "boolean" ||
        typeof claims["jti"] !== "string" ||
        typeof claims["iat"] !== "number" ||
        typeof claims["exp"] !== "number"
      ) {
        return null;
      }

      return {
        sub: claims["sub"],
        iat: claims["iat"],
        exp: claims["exp"],
        jti: claims["jti"],
        tid: claims["tid"],
        roles: claims["roles"] as string[],
        scopes: claims["scopes"] as string[],
        ev: claims["ev"],
        unverified: claims["unverified"],
      };
    } catch {
      // jose throws on invalid/expired tokens — treat all failures as null
      return null;
    }
  }

  // -------------------------------------------------------------------------
  // Access token revocation
  // -------------------------------------------------------------------------

  async function revokeAccessToken(
    jti: string,
    expUnixSeconds: number
  ): Promise<void> {
    // TTL is the token's remaining lifetime, capped at the max access token TTL.
    // When the token would have expired anyway the Redis key auto-deletes,
    // so we never accumulate stale blocklist entries.
    const remainingSeconds = expUnixSeconds - Math.floor(Date.now() / 1000);
    if (remainingSeconds <= 0) {
      // Token already expired — no need to add to blocklist
      return;
    }
    const ttl = Math.min(remainingSeconds, getJwtExpirySeconds());
    await redis.set(`revocation:${jti}`, "1", "EX", ttl);
  }

  // -------------------------------------------------------------------------
  // Refresh token rotation (L2 design §6.4)
  // -------------------------------------------------------------------------

  async function rotateRefreshToken(oldToken: string): Promise<{
    accessToken: string;
    refreshToken: string;
    expiresIn: number;
  }> {
    // Step 1: Atomic DEL — only one concurrent rotation wins
    const pipeline = redis.pipeline();
    pipeline.get(`auth:refresh:${oldToken}`);
    pipeline.del(`auth:refresh:${oldToken}`);
    const results = await pipeline.exec();

    if (!results) {
      throw new UnauthorizedError("Token rotation pipeline failed.");
    }

    const [getResult, delResult] = results;
    const rawPayload = getResult?.[1] as string | null;
    const delCount = delResult?.[1] as number;

    if (rawPayload === null || delCount === 0) {
      // Token not in Redis — check if this is a replay (old token for a
      // session whose family is still alive but the token was already rotated)
      await detectAndHandleReplay(oldToken);
      throw new UnauthorizedError("Refresh token not found or already used.");
    }

    const payload = JSON.parse(rawPayload) as RefreshTokenPayload;

    // Step 2: Verify the session still exists and get its expiry
    const sessionResult = await db.query<{
      expires_at: Date;
      revoked_at: Date | null;
    }>(
      "SELECT expires_at, revoked_at FROM auth.sessions WHERE id = $1",
      [payload.sessionId]
    );

    const session = sessionResult.rows[0];
    if (!session) {
      throw new UnauthorizedError("Session not found.");
    }
    if (session.revoked_at !== null) {
      throw new SessionRevokedError("Session has been revoked.");
    }

    const remainingMs = session.expires_at.getTime() - Date.now();
    if (remainingMs <= 0) {
      throw new UnauthorizedError("Session has expired.");
    }

    const remainingSeconds = Math.floor(remainingMs / 1000);

    // Step 3: Issue new tokens
    const newJti = randomUUID();
    const newToken = randomBytes(32).toString("hex");

    const newPayload: RefreshTokenPayload = {
      ...payload,
      jti: newJti,
    };

    // Step 4: DB transaction — update session JTI atomically, then write new
    // token to Redis only after the DB commit succeeds.
    const client = await db.connect();
    try {
      await client.query("BEGIN");
      await client.query(
        "UPDATE auth.sessions SET refresh_token_jti = $1, last_used_at = now() WHERE id = $2",
        [newJti, payload.sessionId]
      );
      await client.query("COMMIT");
    } catch (err) {
      await client.query("ROLLBACK");
      throw err;
    } finally {
      client.release();
    }

    // Write new refresh token to Redis AFTER DB commit
    await redis.set(
      `auth:refresh:${newToken}`,
      JSON.stringify(newPayload),
      "EX",
      remainingSeconds
    );
    // Secondary index for replay detection
    await redis.set(`auth:token-family:${newToken}`, payload.familyId, "EX", remainingSeconds);
    // Update family set: remove old token, add new token
    await redis.srem(`auth:refresh-family:${payload.familyId}`, oldToken);
    await redis.sadd(`auth:refresh-family:${payload.familyId}`, newToken);
    // Update user-sessions set: remove old, add new
    await redis.srem(`auth:user-sessions:${payload.userId}`, oldToken);
    await redis.sadd(`auth:user-sessions:${payload.userId}`, newToken);

    // Step 5: Fetch user for token issuance
    const userResult = await db.query<{
      id: string;
      tenant_id: string;
      roles: string[];
      email_verified: boolean;
    }>(
      "SELECT id, tenant_id, roles, email_verified FROM auth.users WHERE id = $1",
      [payload.userId]
    );

    const user = userResult.rows[0];
    if (!user) {
      throw new UnauthorizedError("User not found.");
    }

    const accessToken = await issueAccessToken({
      id: user.id,
      tenantId: user.tenant_id,
      roles: user.roles,
      emailVerified: user.email_verified,
    });

    return {
      accessToken,
      refreshToken: newToken,
      expiresIn: getJwtExpirySeconds(),
    };
  }

  // -------------------------------------------------------------------------
  // Replay detection (L2 design §6.4 — REPLAY DETECTION section)
  // -------------------------------------------------------------------------

  async function detectAndHandleReplay(oldToken: string): Promise<void> {
    // The token is NOT in Redis — it was already rotated. Look up the
    // family via a secondary Redis index (auth:token-family:{token} → familyId)
    // that we store at issuance time.
    const familyId = await redis.get(`auth:token-family:${oldToken}`);
    if (!familyId) {
      // No family index — token was never issued or TTL expired naturally.
      // Cannot determine family; fall through to UNAUTHORIZED.
      return;
    }

    // Revoke ALL sessions in this family — a replay means the attacker has
    // a prior token while the legitimate user has a newer one.
    const sessionsResult = await db.query<{ id: string }>(
      `UPDATE auth.sessions
       SET revoked_at = now(), revoked_reason = 'token_replay_detected'
       WHERE family_id = $1 AND revoked_at IS NULL
       RETURNING id`,
      [familyId]
    );

    // Delete all refresh tokens in this family from Redis.
    // We use a Redis Set keyed by familyId (auth:refresh-family:{familyId}) that
    // is maintained at issuance and rotation time. SMEMBERS is O(n) on the family
    // size — avoids a full-keyspace SCAN which would be a DoS vector on large
    // deployments (SCAN iterates every key in Redis regardless of pattern).
    const familySetKey = `auth:refresh-family:${familyId}`;
    const familyTokens = await redis.smembers(familySetKey);
    for (const token of familyTokens) {
      await redis.del(`auth:refresh:${token}`);
      await redis.del(`auth:token-family:${token}`);
    }
    await redis.del(familySetKey);

    if (sessionsResult.rowCount !== null && sessionsResult.rowCount > 0) {
      throw new TokenReplayDetectedError(
        `Token replay detected — ${sessionsResult.rowCount} session(s) in family revoked.`
      );
    }
  }

  // -------------------------------------------------------------------------

  return {
    issueAccessToken,
    issueRefreshToken,
    verifyAccessToken,
    revokeAccessToken,
    rotateRefreshToken,
  };
}

// ---------------------------------------------------------------------------
// Named export for scope resolution — used by auth-service and bootstrap-service
// ---------------------------------------------------------------------------
export { resolveScopes as resolveScopesFromRoles };

// ---------------------------------------------------------------------------
// Re-export errors that callers need
// ---------------------------------------------------------------------------
export { TokenReplayDetectedError, SessionRevokedError };
