/**
 * Type declaration generator for OnePlatform entity schemas.
 *
 * Converts ontology entity definitions fetched from the platform into
 * TypeScript module augmentation declarations, enabling type-safe
 * useQuery<EntityTypeMap["customer"]>("customer") calls in app code.
 *
 * The generated file is a side-effect-free .d.ts — it only augments
 * the @oneplatform/app-sdk module and introduces no runtime code.
 */

// ─── Field type mapping ───────────────────────────────────────────────────────

/**
 * Maps platform fieldType strings to TypeScript primitive types.
 * "enum" is handled specially — per-field enumValues produce a union literal
 * type instead of the fallback "string" here.
 */
const TYPE_MAP: Record<string, string> = {
  text: "string",
  integer: "number",
  float: "number",
  boolean: "boolean",
  datetime: "string", // ISO 8601 string
  json: "Record<string, unknown>",
  uuid: "string",
  array: "unknown[]",
  enum: "string", // overridden per-field when enumValues is present
};

// ─── Field shape ──────────────────────────────────────────────────────────────

export interface EntityField {
  slug: string;
  fieldType: string;
  required: boolean;
  enumValues?: string[];
}

export interface OntologyEntitySchema {
  slug: string;
  fields: EntityField[];
}

// ─── Conversion helpers ───────────────────────────────────────────────────────

/**
 * Converts a single entity field definition to its TypeScript property line.
 *
 * Enum fields with enumValues produce a union literal:
 *   status?: "active" | "inactive" | "pending";
 *
 * All other fields use the TYPE_MAP lookup, falling back to "unknown" for
 * unrecognised fieldType strings so generated code always compiles.
 */
export function fieldToTs(field: EntityField): string {
  let tsType: string;

  if (field.fieldType === "enum" && field.enumValues && field.enumValues.length > 0) {
    // Produce a string literal union from enumValues, e.g. "active" | "inactive"
    tsType = field.enumValues.map((v) => JSON.stringify(v)).join(" | ");
  } else {
    tsType = TYPE_MAP[field.fieldType] ?? "unknown";
  }

  // Optional marker: omit the "?" for required fields so callers must supply them.
  const optional = field.required ? "" : "?";
  return `    ${field.slug}${optional}: ${tsType};`;
}

// ─── Main generator ───────────────────────────────────────────────────────────

/**
 * Generates the full content of an `op-types.d.ts` declaration file from a
 * list of ontology entity schemas.
 *
 * The output augments the @oneplatform/app-sdk module by extending the
 * EntityTypeMap interface, which useQuery<T> uses for type inference.
 *
 * @param entities  Array of entity schemas from GET /api/v1/ontology
 * @returns         TypeScript source string ready to be written to disk
 */
export function generateEntityTypes(entities: OntologyEntitySchema[]): string {
  if (entities.length === 0) {
    return [
      "// Auto-generated by `op sdk generate-types`. Do not edit.",
      "// No ontology entities found — run after defining entity schemas.",
      "declare module \"@oneplatform/app-sdk\" {",
      "  // eslint-disable-next-line @typescript-eslint/no-empty-interface",
      "  interface EntityTypeMap {}",
      "}",
      "",
    ].join("\n");
  }

  const entityInterfaces = entities.map((entity) => {
    const fieldLines = entity.fields.map(fieldToTs);
    // Every entity always has an id field injected by the platform.
    // Only add it if the entity schema does not already declare it.
    const hasId = entity.fields.some((f) => f.slug === "id");
    const allLines = hasId ? fieldLines : ["    id: string;", ...fieldLines];

    return [
      `    ${entity.slug}: {`,
      ...allLines,
      "    };",
    ].join("\n");
  });

  return [
    "// Auto-generated by `op sdk generate-types`. Do not edit.",
    "// Re-run `op sdk generate-types` after changing entity schemas.",
    "declare module \"@oneplatform/app-sdk\" {",
    "  interface EntityTypeMap {",
    entityInterfaces.join("\n"),
    "  }",
    "}",
    "",
  ].join("\n");
}
